### ISSUE TITLE
SigV4 signature doc has some errors

### ISSUE THREAD

**Issue by Gesangvoll** [grafana/k6-docs#1007]
https://k6.io/docs/javascript-api/jslib/aws/signaturev4/sign/ This doc has two places to fix / improve:
1. Typo in the line `import { AWSConfig, SignatureV4 } from 'https://jslib.k6.io/aws/0.7.1/kms.js'`, it should not be kms.js, but signature.js
2. The object definition that `sign()` accepts is incomplete, such as it does not have the `body` for POST request. We should mention that in fact the object is a `HTTPRequest` object that is from http.js, and the fields in the doc should match with the HTTPRequest fields.

**Comment by oleiade** [comment]
Thanks a lot for reporting this @Gesangvoll much appreciated 🙇🏻 
I'm gonna look into addressing those issues indeed!
