### ISSUE TITLE
Document the Elasticsearch output

### ISSUE THREAD

**Issue by ppcano** [grafana/k6-docs#1014]
Add [Elasticsearch](https://www.elastic.co/elasticsearch/) to the list of k6 outputs:

- Write the instructions for the [Elastic extension](https://github.com/elastic/xk6-output-elasticsearch) similar to other [output tutorials](https://k6.io/docs/results-output/real-time/#service).

- List it on the [integrations page of the documentation](https://k6.io/docs/integrations/#result-store-and-visualization).

- Add to [Getting Started - Results Output](https://k6.io/docs/get-started/results-output/#time-series-and-external-outputs)

**Comment by immavalls** [comment]
We'll base this on https://github.com/elastic/xk6-output-elasticsearch

It primarily works with ES cloud: https://cloud.elastic.co/. The extension does not support self-signed certificates (we are probably missing the option to configure `InsecureSkipVerify`, or the ability to pass the RootCA, when using https://github.com/elastic/go-elasticsearch/). ES >=8.0.0 comes with TLS as default. https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html.

**Comment by immavalls** [comment]
The first iteration is on https://github.com/grafana/k6-docs/pull/1104. I am initially adding ES output to the docs.

We still need to create a blog showcasing how to run this extension. Once the blog is ready, I'll add a section similar to https://k6.io/docs/results-output/real-time/timescaledb/#read-more.
