### ISSUE TITLE
Update the AWSv4 authentication page

### ISSUE THREAD

**Issue by sniku** [grafana/k6-docs#1034]
I just noticed that we are recommending the browserified AWS v4 authentication lib [here](https://k6.io/docs/examples/http-authentication/#aws-signature-v4-authentication) instead of our [own jslib](https://k6.io/docs/javascript-api/jslib/aws/) for the same purpose. We should probably update these docs, unless I'm missing something

**Comment by mstoykov** [comment]
Fixed in https://github.com/grafana/k6-docs/pull/1149
