### ISSUE TITLE
Improve wording around graceful stop 

### ISSUE THREAD

**Issue by immavalls** [grafana/k6-docs#1062]
In https://k6.io/docs/using-k6/scenarios/concepts/graceful-stop/ we have

> This option is available for all executors except externally-controlled and allows the user to specify a duration to wait before forcefully interrupting them. The default value of this property is 30s.

Based on feedback from our [community slack](https://k6io.slack.com/archives/C3E688J8Z/p1677677890298869), it isn't clear. 

At the end of the page we have the section [`Additional information`](https://k6.io/docs/using-k6/scenarios/concepts/graceful-stop/#additional-information) which mentions `gracefulRampDown`, which can only be used with https://k6.io/docs/using-k6/scenarios/executors/ramping-vus. 

Proposed wording:

> There is a graceful exit option for all executors except externally-controlled. With ramping-vus, use `gracefulrampdown`, and in all other executors, use `gracefulstop`.

**Comment by MattDodsonEnglish** [comment]
From discussion with @na-- , I realize that `GracefulStop` is not comparable to `gracefulRampdown`. I also realized that `ramping-vus` also has gracefulStop, so I was completely wrong about that!

`gracefulRampdown` is about letting iterations finish in a rampdown. To quote @na--

> when a stage's target value is lower than the previous stage's target, k6 needs to stop some of the VUs are currently running, started during the previous stages; gracefulRampDown controls how long these VUs will have to finish currently running iterations before they are forcefully interrupted

So, I think we can just remove the mention of `gracefulRampdown` before the final section, then add this preceding quote to a final section called 

"Graceful stop".
