### ISSUE TITLE
Document windows commands explicitly in the browser docs

### ISSUE THREAD

**Issue by immavalls** [grafana/k6-docs#1078]
Based on https://community.k6.io/t/issue-using-k6-browser-unknown-module-k6-x-browser/6147/2?u=eyeveebe and some discussions I have had in the community slack (now https://community.k6.io/t/error-typeerror-value-is-not-an-object-undefined-when-i-run-the-example/6175), it would probably be good to document the Windows commands in the getting started guides explicitly.

https://k6.io/docs/javascript-api/k6-browser/get-started/running-browser-tests/

Instead of only:

<img width="778" alt="image" src="https://user-images.githubusercontent.com/4788634/224753208-0eaebe08-11a9-47d7-aee9-696c0f9e629c.png">

Add the equivalents, similar to what we have in https://k6.io/docs/using-k6/environment-variables/#configure-k6-options-with-environment-variables.

<img width="812" alt="image" src="https://user-images.githubusercontent.com/4788634/224753390-600ebefe-e25f-40b6-9895-7ba2e08bde3f.png">

<img width="830" alt="image" src="https://user-images.githubusercontent.com/4788634/224753511-5ab7e096-ccad-4177-b8ee-6410b8ea5b30.png">

Users getting started with the browser don't necessarily go to https://k6.io/docs/using-k6/environment-variables/#configure-k6-options-with-environment-variables

Alternatively mention that environment variables might be set differently based on the OS and link to https://k6.io/docs/using-k6/environment-variables/#configure-k6-options-with-environment-variables

**Comment by immavalls** [comment]
@MattDodsonEnglish What do you think about this one? Should we include different execution options (Bash, Windows, even docker?) on the getting started guides, or better point in the instructions to how to execute for different OS? I can fix this one once we decide what's best.

**Comment by mdcruz** [comment]
@immavalls I've quickly fixed this as part of https://github.com/grafana/k6-docs/issues/1078, as I did a few updates in the k6 browser documentation. Let me know if the change is okay :)

**Comment by immavalls** [comment]
Perfect @mdcruz Thanks!
