### ISSUE TITLE
k6.io GraphQL example shows gRPC example

### ISSUE THREAD

**Issue by vigovlugt** [grafana/k6-docs#1100]
Hello! Just to let you know, the GraphQL example on the homepage of [k6.io](https://k6.io) shows the gRPC example:
![image](https://user-images.githubusercontent.com/16863158/227766455-f3608b4e-e041-4f8a-8f10-dc3679cbad66.png)

**Comment by ppcano** [comment]
@vigovlugt, thanks for taking the time to report this. It should be fixed now.

<img width="1076" alt="Screenshot 2023-03-30 at 06 16 10" src="https://user-images.githubusercontent.com/825430/228727875-c95656a3-f1ef-4e06-88a1-789d282f5840.png">
