### ISSUE TITLE
Docs file structure not suitable for Windows k6-docs/src/data/markdown/docs/20 jslib/01 jslib/01 aws/SecretsManagerClient/04 deleteSecret(secretID, { recoveryWindow: 30, noRecovery: false}}).md

### ISSUE THREAD

**Issue by srperf** [grafana/k6-docs#1115]
Have been trying to clone the repository but this file keeps messing my windows copy and checkout.
k6-docs/src/data/markdown/docs/20 jslib/01 jslib/01 aws/SecretsManagerClient/04 deleteSecret(secretID, { recoveryWindow: 30, noRecovery: false}}).md

$ git clone https://github.com/grafana/k6-docs
Cloning into 'k6-docs'...
remote: Enumerating objects: 30976, done.
remote: Counting objects: 100% (173/173), done.
remote: Compressing objects: 100% (123/123), done.
remote: Total 30976 (delta 76), reused 95 (delta 46), pack-reused 30803
Receiving objects: 100% (30976/30976), 70.27 MiB | 12.88 MiB/s, done.
Resolving deltas: 100% (21524/21524), done.
error: unable to create file src/data/markdown/docs/20 jslib/01 jslib/01 aws/SecretsManagerClient/04 deleteSecret(secretID, { recoveryWindow: 30, noRecovery: false}}).md: Invalid argument
Updating files: 100% (3113/3113), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by oleiade** [comment]
@srperf Looking into it 👀 What is your windows setup, though, especially which terminal do you use, and which git (through what means of installation)? Are you using the git bash project or a dedicated Git client?

 I assume that the format used in the filename is not supported by NTFS or something along those lines 🤞🏻

**Comment by srperf** [comment]
Hey amigo @oleiade 
I am just using https://git-scm.com/ CL client
It totally seems like it is an NTFS situation, it doesn't allow me to direct download that file either 😞

**Comment by ppcano** [comment]
@srperf should be fixed by https://github.com/grafana/k6-docs/commit/ce632ee8919a540c007ff8a5049767b2c8d0fbe5. Please, reopen if the problem persists. 

If this becomes a frequent issue, let's validate filenames with a script such as this [one](https://moritzmolch.com/blog/2508.html).
