### ISSUE TITLE
Enable filtering on extensions 'Explore' page

### ISSUE THREAD

**Issue by javaducky** [grafana/k6-docs#1158]
Add the filter tools to the 'Explore' page, similar to the 'Bundle' page.

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/944496/235913723-9d1db62a-b4ed-4dba-ae69-b155cdcbaa33.png">

**Comment by denis-pp** [comment]
@javaducky If we'll add this filter to the "Explore" page, it almost won't be any differences in content between the "Explore" and "Bundle" pages (just some text at the top and bottom). Maybe it's time to merge these 2 pages into one?

**Comment by javaducky** [comment]
@denis-pp I agree. We'd just need the cards on the Bundle page to include the Github link. I had previously played around with combining the text from both pages, so that should look good.

**Comment by javaducky** [comment]
Closing this.
