### ISSUE TITLE
Incorrect counts when filtering extensions

### ISSUE THREAD

**Issue by javaducky** [grafana/k6-docs#1159]
When removing the category grouping, the count of available extensions is sometimes incorrect. This is due to some extensions appearing in multiple categories. Ideally, the count should reflect the number of unique extensions found.

<img width="1224" alt="image" src="https://user-images.githubusercontent.com/944496/235915116-09a04155-3991-4872-9f5d-c9924d309f83.png">

**Comment by yasell** [comment]
Hi @javaducky! Fixed in #1165, please review

**Comment by javaducky** [comment]
Fixed with #1165
