### ISSUE TITLE
Update k6-browser options documentation after reevaluation

### ISSUE THREAD

**Issue by ka3de** [grafana/k6-docs#1171]
Recently k6-browser options have been reevaluated (see https://github.com/grafana/xk6-browser/issues/854) and a few decisions have been taken which impact the means through which some options are set. Therefore, k6-browser documentation must be updated to reflect these changes with expected release on k6-browser v1.0.0-rc0 (even `main`?) and k6 v0.45.0.

Specifically:
- The current `K6_BROWSER_ENABLED` environment variable will be replaced by browser options inside scenario definitions (see https://github.com/grafana/k6/pull/3036)
- `devtools`, `env` and `proxy` options are no longer supported (`proxy` option might be supported in the future once we have a valid implementation for it).
- `timeout`, `headless`, `debug`, `args`, `ignoreDefaultArgs` and `executablePath` options should now by set through the environment variables `K6_BROWSER_TIMEOUT`, `K6_BROWSER_HEADLESS`, `K6_BROWSER_DEBUG`, `K6_BROWSER_ARGS`, `K6_BROWSER_IGNORE_DEFAULT_ARGS` and `K6_BROWSER_EXECUTABLE_PATH` respectively.

- browser `timeout` option does no longer apply as the default navigation timeout (which is 30s). It only applies for browser initialization/connection actions.
- `slowMo` is not supported at the browser level by now. Its usage and implementation will be reevaluated in order to support it at the `browserContext` level instead (see https://github.com/grafana/xk6-browser/issues/863).

**Comment by inancgumus** [comment]
Closed by #1200 and #1222.
