### ISSUE TITLE
Docs: Migration guide for k6 browser v1.0.0 API

### ISSUE THREAD

**Issue by ka3de** [grafana/k6-docs#1259]
After the recent changes made to k6 browser API, including the scenario browser options (https://github.com/grafana/xk6-browser/pull/876), the abstraction of the browser lifecycle (https://github.com/grafana/xk6-browser/pull/910), and the enforcing of a single `browserContext` per iteration (https://github.com/grafana/xk6-browser/pull/929), current k6 browser scripts API have a few considerable differences from previous versions.

It would probably be helpful for current users to have a migration guide on how to adapt their "old" k6 browser test scripts to the new version.

Note: Final released version might be v.1.0.0 instead of v0.11.0.

**Comment by inancgumus** [comment]
Here's the current outline:

-   Executor and scenario options.
-   Changes in configuring the browser: scenario options.
-   Execution model changes: One browser one browser context.
-   A single scenario can only run contexts in a sequence, not concurrently.
    -   Retrieving the `browserContext` if `newPage` is used, and how we only retrieve the one live browser context.
    -   `browser.close` is no longer needed.
    -   Explain how we now handle the browser lifecycle.
    -   Imports have changed: There is no more `chromium` browser type etc, but `browser`.
-   Environment variable changes.
    -   No more `K6_BROWSER_ENABLED` flag.
-   Some of the [cmd flags don't work](https://raintank-corp.slack.com/archives/C040VPWDQG6/p1689348431447859) e.g.: `-u`, `-v` and `-d`.
