### ISSUE TITLE
How to catch HTTP exceptions?

### ISSUE THREAD

**Issue by rugleb** [grafana/k6-docs#1313]
Hi!
I'm trying to catch error during my backand startup in `setup` stage:
```js

const waitServer = (maxAttempts) => {
  for (let i = 0; i < maxAttempts; i++) {
    console.log(i)
    try {
      http.get('http://api:8080/health')
    } catch (e) {
      console.log(`Check health failed: ${e}`)
      sleep(1)
      continue
    }
    console.log('ok')
    return
  }
  console.log('fail')
}

export function setup() {
  waitServer(5)
}
```

I want sleep `maxAttempts` times after fail, but can't catch exception (logs):
```
time="2023-09-05T22:20:31Z" level=info msg=0 source=console
time="2023-09-05T22:20:31Z" level=warning msg="Request Failed" error="Get \"http://api:8080/health\": dial tcp 172.18.0.6:8080: connect: connection refused"
time="2023-09-05T22:20:31Z" level=info msg=ok source=console
time="2023-09-05T22:20:31Z" level=warning msg="Request Failed" error="Post \"http://api:8080/reports/account\": dial tcp 172.18.0.6:8080: connect: connection refused"
```

How to catch HTTP exceptions? How to wait backend with long-starting backend (via docker-compose)?
Thx.

PS: I'm not sure that It's ok for open issue in this repo, but docs nothing tell about catching HTTP errors.

**Comment by heitortsergent** [comment]
Hi @rugleb! You could check out the [Checks docs page](https://k6.io/docs/using-k6/checks/#check-for-http-response-code) for an example of how to check for an HTTP request status code, would that help you catch the exception you're looking for?

```js
import { check } from 'k6';
import http from 'k6/http';

export default function () {
  const res = http.get('http://test.k6.io/');
  check(res, {
    'is status 200': (r) => r.status === 200,
  });
}
```

Also, sorry for the delay in replying to you here. For help with using k6 specifically, I'd also recommend posting on the [Community Forums](https://community.grafana.com/), and someone should be able to help you there as well. :)

**Comment by zimmj** [comment]
This sounds more like a startup issue, which can be handled as well in docker compose itself,

I am guessing that k6 is started in the same compose file, therefore you can let docker wait for the Back-End to be started up before it's start k6:

[Docker Startup order](https://docs.docker.com/compose/startup-order/)

There you can wait for your healthy statement.

Other way, would be to write a while waiting loop:
```
while(call to Backend is unhealthy){
   sleep(1)
}
```

**Comment by heitortsergent** [comment]
Thanks for chiming in @zimmj!

@rugleb I'm going to close this issue for now, please let us know or open a thread in the [Community Forums](https://community.grafana.com/) if you have any other questions about how to use k6. 🙏
