### ISSUE TITLE
New auth methods and headers for xk6-output-prometheus-remote

### ISSUE THREAD

**Issue by heitortsergent** [grafana/k6-docs#1360]
- https://github.com/grafana/xk6-output-prometheus-remote/pull/143
- https://github.com/grafana/xk6-output-prometheus-remote/pull/145
- https://github.com/grafana/xk6-output-prometheus-remote/pull/147

**Comment by codebien** [comment]
Closed by https://github.com/grafana/k6-docs/pull/1366
