### ISSUE TITLE
Document that gRPC's how to use well know types (`google.protobuf.*`)

### ISSUE THREAD

**Issue by olegbespalov** [grafana/k6-docs#1378]
# What?

In k6 v0.47 we fixed the unmarshaling of the well-known GRPC types (`google.protobuf.*`)

But their usage needs to be clarified for our customers. 

E.g.:
* https://github.com/grafana/xk6-grpc/issues/55
* https://community.grafana.com/t/k6-is-sending-empty-text-for-datetime-string/105656

We need to provide more examples and document them.

# Why?

It needs to be clarified for our users.

**Comment by mstoykov** [comment]
Just noting that in particular they are marshalled and unmarshalled to their JSON representation as I found out in https://github.com/grafana/k6/issues/3426
