### ISSUE TITLE
Document `net/grpc` uses the JSON encoding of protobuf

### ISSUE THREAD

**Issue by mstoykov** [grafana/k6-docs#1443]
In a recent issue https://github.com/grafana/k6/issues/3426, the user was confused as the way the type is represented in JSON is not ... obvious. It also took me quite a while to figure out this was the issue and multiple readings of a different issues.

It will be nice to have this better documented, even with some examples (maybe this one)

**Comment by olegbespalov** [comment]
Somehow duplicates the https://github.com/grafana/k6-docs/issues/1378
