### ISSUE TITLE
Document the querybuilder jslib

### ISSUE THREAD

**Issue by simskij** [grafana/k6-docs#145]
Requested in https://github.com/loadimpact/jslib.k6.io/issues/4
Implemented in https://community.k6.io/t/http-get-query-params/120

I'm thinking that we need an example of this in the examples section.
@legander and @allansson; would you mind assisting with this?

**Comment by legander** [comment]
Sure thing. Haven't listed the URL utils as supported/available yet though because I want to run some testing internally first. But I can create a new example section in the docs for this when making it available for public 👍

**Comment by ppcano** [comment]
@legander added the example via #182. 

It is pending to document the new methods on [jslib.utils API](https://k6.io/docs/javascript-api/jslib/utils/).
