### ISSUE TITLE
Browser: Missing warning boxes

### ISSUE THREAD

**Issue by inancgumus** [grafana/k6-docs#1583]
The browser team uses [the `BWIPT` marker](https://github.com/search?q=repo%3Agrafana%2Fk6-docs%20BWIPT&type=code) to add a warning box for a missing/problematic feature. 

* This feature [is used to work](https://k6.io/docs/javascript-api/k6-experimental/browser/newcontext/) in the older k6 docs.
* The old k6 docs used [this code](https://github.com/grafana/k6-docs/blob/7a965b56064313c1e906fff938134cb19ddc8a01/src/components/shared/tooltip/bwipt/bwipt.js#L1-L37) to generate the warning box.
* The warning box is clickable and redirects to a relevant issue in the xk6-browser repository.

Hopefully, this feature might be added back in using [Hugo's shortcodes](https://gohugo.io/content-management/shortcodes/) 🤞

## Before

<img width="873" alt="Screenshot 2024-05-08 at 15 49 24" src="https://github.com/grafana/k6-docs/assets/621232/18394897-ef58-40c1-bc3f-fa91f941361e">

## After

<img width="775" alt="Screenshot 2024-05-08 at 15 50 05" src="https://github.com/grafana/k6-docs/assets/621232/428774fd-43be-41cc-bfd0-5b581d968d1c">

----

```[tasklist]
### Tasks
- [ ] grafana/website#19916
- [ ] #1599
```

**Comment by heitortsergent** [comment]
@jdbaldry is this something you could help us with? I was wondering if we should keep track of this here or on the website repo.

**Comment by heitortsergent** [comment]
@inancgumus do you think we can close this issue? I think updating it to use Grafana Labs colors can be separate from this.

**Comment by inancgumus** [comment]
@heitortsergent Yep, we're all good 👍
