### ISSUE TITLE
Update "Running Large Tests" article

### ISSUE THREAD

**Issue by sniku** [grafana/k6-docs#208]
With several new features in k6, it's time to re-run the performance tests and update the results. We should be able to squeeze significantly more requests/VUs from a single machine now.

**Comment by FloorD** [comment]
Reference: https://talawah.io/blog/extreme-http-performance-tuning-one-point-two-million/

**Comment by immavalls** [comment]
This is being worked in https://github.com/grafana/k6-docs/pull/992
