### ISSUE TITLE
Versioned documentation

### ISSUE THREAD

**Issue by na--** [grafana/k6-docs#242]
We make k6 API changes in every k6 release, but in contrast to pretty much all other developer tools, we don't have versioned documentation for them... Here are some examples:
- https://docs.influxdata.com/influxdb/v1.8/, https://docs.influxdata.com/influxdb/v2.0/, etc.
- https://docs.timescale.com/latest/main, https://docs.timescale.com/v2.0/main, etc.
- https://docs.influxdata.com/telegraf/v1.17/, https://docs.influxdata.com/telegraf/v1.13/, etc.
- https://grafana.com/docs/loki/latest/, https://grafana.com/docs/loki/v2.0.1/, etc.
- https://pkg.go.dev/github.com/loadimpact/k6, https://pkg.go.dev/github.com/loadimpact/k6@v0.27.0, etc.
- https://gatling.io/docs/current/, https://gatling.io/docs/3.4/, etc.

I could go on, but we're pretty much the exception of having non-versioned docs... This also causes us to have to preface any doc additions with "since k6 vX.Y.Z`, ..." for the changes on every release, which is a PITA when we don't forget it, and not always easy or possible to do (e.g. https://github.com/k6io/docs/pull/235)

We talked about this before moving to the new docs to this new repo, but nothing was done then... The original idea was that that the k6 JS API (i.e. approximately https://github.com/k6io/docs/tree/master/src/data/markdown/docs/02%20javascript%20api) would live in the k6 repo, and when building the docs, we'll just clone the k6 repo and copy the versioned files from. Something like this:
```bash
git clone https://github.com/loadimpact/k6.git
cd k6
# This would be in some sort of loop, of course
git checkout v0.30.0
cp -R docs "src/data/markdown/docs/02 javascript api/v0.30.0/"
git checkout v0.31.0
cp -R docs "src/data/markdown/docs/02 javascript api/v0.31.0/"
```

**Comment by na--** [comment]
As a great bonus, this will force us to write the documentation for every k6 change and new together with its code changes, as a part of the same k6 pull request. That means no more delayed documentation...

**Comment by ppcano** [comment]
I think the problem has always been prioritization.

> As a great bonus, this will force us to write the documentation for every k6 change and new together with its code changes, as a part of the same k6 pull request. That means no more delayed documentation

I disagree with the argument that moving the markdown docs to the k6 repo is the solution, neither the problem, of the delayed documentation. 

On the other hand, this requirement might add additional complexity. I much prefer to let it where it is.

Also, a new feature or change should not be only about documenting the Javascript API, but other guides and examples.

**Comment by na--** [comment]
> I think the problem has always been prioritization.

Fair enough, but do you agree that the time has finally come for making this a reality, i.e. prioritizing it towards the top?

> I disagree with the argument that moving the markdown docs to the k6 repo is the solution, neither the problem, of the delayed documentation.

I am pretty sure it heavily contributes to the problem, and I'm speaking from personal experience and from observing these processes first- and second-hand.

> Also, a new feature or change should not be only about documenting the Javascript API, but other guides and examples.

IIRC we discussed this originally - the parts of the documentation for which it makes sense to be versioned together with the k6 versions (options, JS API, _maybe_ examples) can be in the k6 repo, while the parts of the docs that shouldn't be versioned can be in this repo. I imagine that would have been much easier if we had versioned things from the start, but it's certainly doable now... 

> On the other hand, this requirement might add additional complexity. I much prefer to let it where it is.

And I much, much prefer the alternative :wink: :man_shrugging: But if the developer experience is good enough, I'm willing to compromise again and not insist terribly hard on this point, as long as we have versioned documentation at last...

**Comment by simskij** [comment]
@na-- 

> I am pretty sure it heavily contributes to the problem, and I'm speaking from personal experience and from observing these processes first- and second-hand.

I don't want to dig too deep into this as I'm pretty sure we'll end up in the exact same positions as we are right now. 

> as long as we have versioned documentation at last...

As I mentioned earlier in a separate discussion, the docs are in fact already versioned with the granularity of minor versions, using tags. We started this approach with v0.30.0. 

As the first iteration of such a solution, we could at least add a table somewhere in the docs with direct links to the GitHub files of each such commit. I know it's far from the **ideal** solution, but it's a work-around that at least solves the immediate problem of not being able to find docs for your version **at all**.

@ppcano 

> On the other hand, this requirement might add additional complexity.

I agree with this part. It will indeed add complexity. I'm not sure how much, but at least to some degree. Maybe we should set aside some time to explore how other open-source projects solve this? Given the extensive list @na-- posts in the initial comment, it feels like it's a "solved problem", don't you think?

> I much prefer to let it where it is.

Here I kind of disagree. Given how fast we iterate upon the functionality of k6, and how many users we have that stay on older versions, this is already somewhat of a problem, and will definitely increase going forward. However, I think the table linking to the tags, as I propose above, is good enough for now.

**Comment by na--** [comment]
>  Given the extensive list @na-- posts in the initial comment, it feels like it's a "solved problem", don't you think?

FWIW, this was literally me typing `<OSS project I could think off the top of my head> docs` in google and literally every single project I thought of except 1 had versioned documentation... I didn't run out of such projects, I just decided to stop looking.

**Comment by na--** [comment]
Here are some more... Almost every language and language framework is like this, for a good reason, and in most respects k6 is much closer to them than to a normal CLI tool:
- https://pkg.go.dev/net/http, https://pkg.go.dev/net/http@go1.15.5, etc.
- https://docs.python.org/3/, https://docs.python.org/3.9/, etc.
- https://docs.djangoproject.com/en/3.1/, https://docs.djangoproject.com/en/3.0/, etc.
- https://docs.celeryproject.org/en/stable/, https://docs.celeryproject.org/en/master/index.html, https://docs.celeryproject.org/en/4.0/
- https://kubernetes.io/docs/home/, https://v1-19.docs.kubernetes.io/docs/home/, etc. 
- https://ffmpeg.org/doxygen/trunk/index.html, https://ffmpeg.org/doxygen/4.0/index.html, etc.
- react used to do it until v16.8 (https://reactjs.org/versions/) but seem to have stopped recently :sweat_smile: 
- rust just mention in what version a particular a particular feature appears in in the upper right corner, which I guess works for them, given their stability guarantees, e.g. https://doc.rust-lang.org/std/iter/struct.Map.html vs https://doc.rust-lang.org/std/iter/trait.Sum.html
- https://ruby-doc.org/core-3.0.0/, https://ruby-doc.org/core-2.7.2/, etc.
- https://ziglang.org/documentation/master/, https://ziglang.org/documentation/0.7.0/, etc.
- https://docs.locust.io/en/stable/, http://docs.locust.io/en/1.4.3/, etc.

**Comment by ppcano** [comment]
> Fair enough, but do you agree that the time has finally come for making this a reality, i.e. prioritizing it towards the top?

Agree. 

> Given how fast we iterate upon the functionality of k6, and how many users we have that stay on older versions, this is already somewhat of a problem, and will definitely increase going forward

@simskij  I didn't mean to go without versioning. I referred to let the markdown files in this repo instead of moving them to k6.

**Comment by simskij** [comment]
Then it sounds like we're in a rough agreement at least 👍🏼

**Comment by ppcano** [comment]
The documentation supports versioning the `Javascript API` section since v0.31. Closing it.
