### ISSUE TITLE
Rework the table in results output

### ISSUE THREAD

**Issue by mstoykov** [grafana/k6-docs#292]
The table used to say `Plugin` which is totally wrong and now it says `Output` but lists things that aren't Outputs but services that work with one of our outputs. 

@imiric thinks it should just be the list of outputs and on the outputs page we should list the services it works with (StatsD is compatible with a lot of stuff for example). I have the feeling that this will hurt the findability of the supported ones.

Looking at the pages I would also prefer if we cross link between them and the cloud APM support on the top as if someone googles `k6 datadog` they might land one of the two pages.

_Originally posted by @MStoykov in https://github.com/k6io/docs/pull/276#r620315942_

**Comment by simskij** [comment]
>  I have the feeling that this will hurt the findability of the supported ones.

I think so as well. Discoverability would suffer if we did that.

> Looking at the pages I would also prefer if we cross link between them and the cloud APM support on the top as if someone googles k6 datadog they might land one of the two pages.

Agreed

**Comment by imiric** [comment]
> Discoverability would suffer if we did that.

Couldn't this be addressed by simply listing the services supported by each true output below it on the "Results output" page, and linking to the same page with URI fragments (e.g. `/results-visualization/statsd#datadog`)? Though we should probably spiff up the output table to look nicer with this format instead of the current single-row style.

**Comment by MattDodsonEnglish** [comment]
This issue seems irrelevant now.

We have separate pages for each type of output, and extensions are separated in their own  docs.

 When someone in this thread has a moment to switch context and go back in memory, can they confirm that this issue is no longer needed?
