### ISSUE TITLE
Show k6 extension type on Ecosystem page

### ISSUE THREAD

**Issue by imiric** [grafana/k6-docs#303]
Since we now have more than one extension type it would be useful to show whether an extension is a `javascript` or an `output` type on the [Ecosystem](https://k6.io/docs/ecosystem/) page.

We'd need to add a new `type` property to [src/data/ecosystem/extensions.js](https://github.com/k6io/docs/blob/9e44322afddc3f1064f2300c0e2516d3ccf8ea58/src/data/ecosystem/extensions.js) for each extension. This could be rendered as simply "Type: JavaScript" in a small font under the extension name, but it would be nicer if we'd show small icons instead next to the name (e.g. `[JS]`, `[Out]`) to avoid cluttering each element.

In the future it would be good if extensions were filterable by type and category, but that can be done separately.

**Comment by simskij** [comment]
Categories are already there, just not enabled yet. But yeah, having type would be great as well. @vi-nastya can you assist in implementing this? @lnikell can probably assist with what icons to use. I'm thinking something along the lines of `<>` and `->`, wdyt? I'll take care of assigning types to all the existing extensions once we've got things up and rocking.

Thanks 👍🏽

**Comment by bolotskydev** [comment]
@imiric I see this is still relevant despite how old the feature request is. I'll mention you in PR with the necessary changes to fill up the extension types 👍
