### ISSUE TITLE
k6 Cloud: Prometheus Remote Write Integrations & Supported APMs

### ISSUE THREAD

**Issue by ppcano** [grafana/k6-docs#310]
I didn’t immediately understand how the [Prometheus Remote Write integration](https://k6.io/docs/cloud/integrations/cloud-apm/prometheus-remote-write/) works. This issue proposes some changes to the documentation to make more clear the connection between the PRWrite integration and Cloud APM providers. 

### Now

- Cloud APM
  - DataDog
  - AzureMonitor
  - Prometheus Remote Write (NewRelic & Grafana Cloud Prometheus)

I think the current docs are mixing two different concepts:

1 - The Cloud APM integrations: NewRelic & Grafana Cloud Prometheus.
2 - The Prometheus Remote Write Integration allows exporting the k6 cloud metrics to a Remote Endpoint Backend.

### Proposal

I suggest split the documentation as follow:

- Prometheus Remote Write

- Cloud APM
  - Azure Monitor
  - DataDog
  - Grafana Cloud Metrics
  - NewRelic
	

The Prometheus Remote Write page will describe that k6 cloud metrics can be exported to any storage supporting the Prometheus Remote Endpoint integration. The [current list](https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage) is large. 

Later on, if a k6 cloud customer asks for one integration, we can test it and write the proper instructions.

**Comment by mostafa** [comment]
I also suggest this categorization style:

**Comment by mostafa** [comment]
Good idea! Although the articles for vendors and RW would be very short if split PRW article into 3 separate articles.

I might also suggest this categorization style, but it only makes sense if we are planning to add more protocols.

Cloud APM:
  - Supported protocols (in case we want to add others like statsd, ...)
    - Prometheus Remote Write
    - _StatsD_
    - ...
  - Supported providers:
    - Azure Monitor
    - DataDog
    - Grafana Cloud Metrics
    - NewRelic

**Comment by ppcano** [comment]
Closed by https://github.com/grafana/k6-docs/pull/378
