### ISSUE TITLE
Document --quiet option

### ISSUE THREAD

**Issue by ppcano** [grafana/k6-docs#315]
The [k6 options docs](https://k6.io/docs/using-k6/options/) should document the `--quiet/-q` option that disables the progress update bar on the console output.

See the difference when running a simple script.

```
k6 run script.js -d 20s
k6 run script.js -d 20s --quiet
```

The command is valid for `k6 run` and `k6 cloud` commands.

**Comment by imrishabh18** [comment]
@FloorD Can I take this up? And can you guide me what should I look into to resolve this issue please.

**Comment by ppcano** [comment]
@imrishabh18 updated the issue description.

**Comment by ppcano** [comment]
closed by #417
