### ISSUE TITLE
Explain usage of encodeURIComponent

### ISSUE THREAD

**Issue by FloorD** [grafana/k6-docs#322]
We need to add information about, and explanations around, encodeURIComponent for examples where query params are utilized

Comment from a customer:
> ...I tried to test an end-point which looks like that: http://host/api/search?key=value using http.get(endpoint). It works fine if the value doesn't include a whitespace, but of course works well if the whitespace is replaced by %20. This maybe could be written in the documentation as well.

**Comment by ppcano** [comment]
Closing as duplicated  of https://github.com/grafana/k6-docs/issues/204
