### ISSUE TITLE
Document `config.json`

### ISSUE THREAD

**Issue by FloorD** [grafana/k6-docs#325]
For https://k6.io/docs/using-k6/options#config add an example file as "An example of a config file is available here" currently leads nowhere.

**Comment by MStoykov** [comment]
It probably needs to go to the `config.json` file which is the second example in this [section](https://k6.io/docs/using-k6/options/#using-options)

**Comment by monizb** [comment]
Hi! Can I take up this issue?

**Comment by ppcano** [comment]
@monizb, you are welcome! Let us know if you have any questions.

**Comment by monizb** [comment]
> @monizb, you are welcome! Let us know if you have any questions.

Thank you! I did indeed have a question about this, do you want me to link that part to the [section](https://k6.io/docs/using-k6/options/#using-options) or to the config.json file itself? If its the latter, would that be possible without a header tag?

**Comment by ppcano** [comment]
Yes. Ideally, to the `config.json` example. 

I think you can wrap the previous description around a `<div id="config-json-example"` and use an anchor link.
