### ISSUE TITLE
Move JSLib documentation to the regular docs

### ISSUE THREAD

**Issue by simskij** [grafana/k6-docs#331]
@sniku already did this for some of the libs. In the end, `https://jslib.k6.io/` without any further path args should redirect to a page in the regular docs.

**Comment by na--** [comment]
Hmm a big :+1: for improving the docs, but I am not sure about this bit:

> In the end, `https://jslib.k6.io/` without any further path args should redirect to a page in the regular docs.

Some sort of an index like the current one seems very valuable to me... :man_shrugging:  By all means, we can add docs links for every library and more examples on top of that, but straight-up redirecting redirecting people to the docs seems a bit counter-productive.

**Comment by simskij** [comment]
> Hmm a big 👍 for improving the jslib docs, but I am not sure about this bit:
> 
> > In the end, `https://jslib.k6.io/` without any further path args should redirect to a page in the regular docs.
> 
> Some sort of an index like the current one seems very valuable to me... 🤷‍♂️ By all means, we can add docs links for every library and more examples on top of that, but straight-up redirecting people to the docs seems a bit counter-productive.

I'm thinking that it should be a "landing page" for jslib ofc, not just straight-up the docs start page. Think of the first step as just moving what's currently on jslib.k6.io/index.html to (pseudo-url) k6.io/docs/jslib

**Comment by MStoykov** [comment]
As a single data point, I am not really happy when sites do this, as I sometimes/constantly opening multiple tabs from a page and then I go through them one after the other, usually with some time in between.

If I am researching k6 and I open the docs and jslib and the community forum and then I start going through them ... I might be kind of confused that moving from the docs to the jslib site tab leads me to a doc page, again. 

I do routinely wonder if I just didn't click the link with the middle mouse button, or if the link didn't support it and look for the tab before going back clicking on the link and realize that it just redirects me to a page I was *not expecting*.

**Comment by na--** [comment]
> I'm thinking that it should be a "landing page" for jslib ofc, not just straight-up the docs start page. Think of the first step as just moving what's currently on jslib.k6.io/index.html to (pseudo-url) k6.io/docs/jslib. But I'm definitely open to reconsider :sweat_smile:

What would `https://jslib.k6.io/` contain then? If it just redirects you to `https://k6.io/docs/jslib`, this doesn't seem very user-friendly and will just add confusion. I'm fine with the docs also having a page that explains what JS lib is, and a sub-page for every library in JS, but the index page of jslib should still be _on_ jslib.

**Comment by simskij** [comment]
That's the whole reason behind the suggestion though; I don't think it needs its own index page at all.

The behavior I'm suggesting is the same as https://go.k6.io/, but instead of redirecting to GitHub, it would redirect to the jslib docs. The libs themselves would still be available at the same URLs though.

**Comment by na--** [comment]
> is the same as https://go.k6.io/

No, it isn't, it's actually quite the opposite :sweat_smile: 

https://go.k6.io doesn't host anything, it is just a vanity URL that redirects both Go and browsers to the actual place where the code is hosted, GitHub. 

https://jslib.k6.io hosts the actual JS libraries, and having an index in such sites is very valuable and useful to me as a user. So, if anything, I am for adding more indexes (e.g. for individual libraries, I can't see the files in https://jslib.k6.io/httpx and https://jslib.k6.io/httpx/0.0.3/), not removing the one paltry index we currently have and redirecting to the docs...

**Comment by MattDodsonEnglish** [comment]
I think it's convenient to separate these sites, and I'd prefer no redirect. Like na--, I like having the index.

Going to close this, but I'm fine to reopen it sometime.
