### ISSUE TITLE
Equal sign in anchor link breaks the page

### ISSUE THREAD

**Issue by sniku** [grafana/k6-docs#355]
Example link: https://k6.io/docs/testing-guides/running-large-tests/#compatibility-mode=base

![image](https://user-images.githubusercontent.com/442646/126283817-434265af-754c-48ce-bc65-89edb104c0be.png)

Another example: https://k6.io/docs/#equal-sign-in-anchor=breaks-the-page

**Comment by MStoykov** [comment]
This can be fixed through escaping the `=` as shown in 
![image](https://user-images.githubusercontent.com/312246/126283981-bcf356af-3aca-496c-a34d-2060205cfddc.png)

**Comment by simskij** [comment]
@MStoykov Good find! Should probably be done as part of the render though rather than in the markdown. Wdyt @BolotskyDev and @vi-nastya?

**Comment by BolotskyDev** [comment]
Thank you guys for reporting the issue! @simskij @vi-nastya leave the rest to me, will fix it later today 👍

**Comment by BolotskyDev** [comment]
@imiric made a typo during solution refactoring 😒  here is a follow up: #361
