### ISSUE TITLE
Bamboo integration guide

### ISSUE THREAD

**Issue by codebien** [grafana/k6-docs#407]
A user, from the forum, [requests](https://community.k6.io/t/is-there-an-integration-for-bamboo/2212) a guide for integrating [Bamboo CI](https://www.atlassian.com/software/bamboo) with k6. We should create one and add the link in the following sections:

* https://k6.io/docs/integrations/#continuous-integration-and-continuous-delivery
* https://k6.io/docs/testing-guides/automated-performance-testing/#see-also

**Comment by ppcano** [comment]
A [Bamboo guide](https://k6.io/blog/integrating-k6-with-bamboo/) is now available.
