### ISSUE TITLE
[Feature Request]: Add Documentation Template as per new Github Issue forms

### ISSUE THREAD

**Issue by Rutam21** [grafana/k6-docs#465]
### Feature Description

GitHub has recently rolled out a public beta for their issue forms feature. This would allow us to create interactive issue templates and validate them.

K6 Docs currently doesn't use a documentation template format. The task is to create a GitHub issue form for documentation for this repository.

### Suggested Solution (optional)

A `documentation.yaml` file should be added to be used as the default template for raising any documentation requests for the repository.

 - [x] Prepare documentation issue form in .github/ISSUE_TEMPLATE/documentation.yaml

**Comment by ppcano** [comment]
Closing it for the reasons mentioned at #467
