### ISSUE TITLE
Explain details about the k6 architecture

### ISSUE THREAD

**Issue by na--** [grafana/k6-docs#512]
We don't explain in enough details what the k6 VUs actually are, and how the whole test execution is structured. https://k6.io/docs/using-k6/test-life-cycle/ explains some things, but probably not in enough detail for advanced users, so they can get a good mental model of why things are the way they are, and why certain restrictions need to be in place.

https://github.com/grafana/k6/issues/2267 is an example of this problem, but we've had many other similar questions and issues before. Not to mention that such a page might also be helpful for potential k6 contributors, extension writers, as well as people wanting to squeeze the maximum performance out of k6 itself and understand pages like https://k6.io/docs/using-k6/javascript-compatibility-mode/

**Comment by MStoykov** [comment]
connected issue with some more examples https://github.com/grafana/k6-docs/issues/148

**Comment by na--** [comment]
I'll close this one in favor of the old one and edit is slightly
