### ISSUE TITLE
Search field overlapping the header menu

### ISSUE THREAD

**Issue by oleiade** [grafana/k6-docs#543]
Hi folks,

Today, I've noticed what could potentially be an unwanted behavior on the [documentation website](https://k6.io/docs). In my daily work setup, consisting of having two Microsoft Edge windows side by side, occupying each half of my 1440p screen, the search field of the documentation overlaps with the header menu. See the following screenshot:

![image](https://user-images.githubusercontent.com/690867/149098528-47dbdd86-1375-4370-b101-899e7ab59802.png)

Here's all the useful context info I can think of: I'm on Windows 11, using the latest version of Edge, displaying on a dual 1440p display, and using the Powertoys windows manager. Let me know if you need any more information from me.

**Comment by imiric** [comment]
I can confirm this issue when using 150% zoom with Chromium 96 and Firefox 94 on Linux.

This page also has an unnecessary horizontal scrollbar which shifts the page slightly when using middle-click scrolling.
