### ISSUE TITLE
Tables shrink horizontally and cut out text content: although sufficient screen space is available  

### ISSUE THREAD

**Issue by oleiade** [grafana/k6-docs#545]
Hi folks,

Today, I've noticed what could potentially be an unwanted behavior on the [documentation website](https://k6.io/docs/javascript-api/k6-http/response/). In my daily work setup, consisting of having two Microsoft Edge windows side by side, occupying each half of my 1440p screen, the tables seem to shrink horizontally, cutting out content in the process, although there is still plenty of screen space available. See the following screenshot:

![image](https://user-images.githubusercontent.com/690867/149299299-e3ffc119-96b9-4c6a-b5a5-275171e06ab8.png)

In this screenshot, you can notice that the last column of the table does not appear to behave in a "responsive" way. The textual content of it is cutout. Also notice that there is still plenty of horizontal space left on its right side. Thus, I wouldn't expect the table to shrink yet, and if it did, I wouldn't expect the content to be affected.

Here's all the useful context info I can think of: I'm on Windows 11, using the latest version of Edge, displaying on a dual 1440p display, and using the Powertoys windows manager. Let me know if you need any more information from me.

**Comment by bolotskydev** [comment]
Intended behavior. On this resolution table becomes horizontally scrollable, and the space on the right side is reserved for optional table of content.
