### ISSUE TITLE
Page going blank after loading on a particular link

### ISSUE THREAD

**Issue by mstoykov** [grafana/k6-docs#578]
If you open `https://k6.io/docs/testing-guides/running-large-tests/#:~:text=Params.responseType.` (first noticed in this [community forum post](https://community.k6.io/t/correlation-on-discardresponsebodies-enable-response/3036/3) the page first loads and then goes blank with the following in the console 
![image](https://user-images.githubusercontent.com/312246/155496492-b247da71-4421-4364-b20f-2a5835676648.png)

I can't figure out how to generate this URL, but arguably the page going blank instead of giving an error (Or even *nothing* happening) is pretty bad.

**Comment by bolotskydev** [comment]
The issue is no longer reproducible.
