### ISSUE TITLE
Complete xk6-browser API docs

### ISSUE THREAD

**Issue by imiric** [grafana/k6-docs#582]
[The current xk6-browser API docs](https://k6.io/docs/javascript-api/xk6-browser/) are incomplete. After the layout changes in #508 by @ppcano are done, the xk6-browser team should work on adding missing documentation, and notices for methods not yet implemented.

I don't think we should link to https://playwright.dev/ at all. The "rough compatibility" notice should be enough for informational purposes, and since it is a _rough_ compatibility, we shouldn't link directly to Playwright docs, but simply describe what we currently have, and what's in the pipeline to be implemented, along with links to any related open issues, so users can follow them.

Since this will be a long task to finish, maybe we can split it up, work gradually on it and release it incrementally.

Linked Issues:
- https://github.com/grafana/xk6-browser/issues/430
- https://github.com/grafana/xk6-browser/issues/441

**Comment by ankur22** [comment]
Open Branches:
- 
- https://github.com/grafana/k6-docs/commits/docs/582-xk6-browser

PRs:
- https://github.com/grafana/k6-docs/pull/642
- https://github.com/grafana/k6-docs/pull/508

**Comment by ankur22** [comment]
> @ankur22 should we close this issue and if necessary, open more concrete issues?

Yep, good idea
