### ISSUE TITLE
Reuse meta-description as a top-level page summary

### ISSUE THREAD

**Issue by MattDodsonEnglish** [grafana/k6-docs#594]
The doc pages have an `excerpt` field in their YAML front matter. The `excerpt` describes the page's contents in one or two sentences. The site generator uses this to create a `description` HTML meta tag.

Since the site already provides a page-level summary for web crawlers, why not let humans read it too? The `excerpt` could provide a "TL;DR" at the front of each page, making it easier for readers to understand whether they want to read further.

Since the excerpt already exists, this work is almost "free." As I see it, there are two steps:

1. Someone needs to read through the excerpts and make sure they're human-readable, i.e. grammatical, useful, and accurate. Social sites already use meta descriptions for previews, so users already read it when someone shares the k6 docs on Slack, Discord, et cetera.

I can do this as I learn the documentation set. Maybe I'd make some excerpts a bit longer. Current guidelines recommend between 50-160 characters.[^1]

2. After that, k6 would need to add a single line to the doc's template, inserting the excerpt at the top. This screenshot isn't how it would really work, but it gives the general idea:

![Uses the excerpt as a variable](https://user-images.githubusercontent.com/47385188/159058839-05ac114e-3d9c-4071-b947-f4c5f339c53f.png)

[^1]https://moz.com/learn/seo/meta-description

**Comment by MattDodsonEnglish** [comment]
When I made  issue https://github.com/grafana/k6-docs/issues/600 , I discovered another place where the `excerpt` text could be used.

![image](https://user-images.githubusercontent.com/47385188/161150399-32a2eed8-3a6f-4517-9a88-bd41136e1bad.png)

**Comment by ppcano** [comment]
The `excerpt` is the description shown on the search engine result pages (SERP). 

![Screenshot 2022-08-05 at 18 46 25](https://user-images.githubusercontent.com/825430/183123616-1aa36d75-0863-4611-9d36-3677d44b38b8.png)

I have some doubts about reusing this content:
 - I doubt we always want to show it as TL;DR on the front of the page. It should be optional.
 - Even if we want to show it for some page, are we confident that we want to use the same content for Search descriptions as TL;DR? 
 

2 -  The layout of the “category pages" should be improved.

<img width="298" alt="Screenshot 2022-08-08 at 09 27 39" src="https://user-images.githubusercontent.com/825430/183363249-35476279-e083-4e91-ba2c-cca85ffc50f0.png">

Note that this could be solved by creating a markdown file for each category page. This is possible today, but we are not creating those pages. 

This proposal could be a good solution to explore. I like the idea of using a frontmatter property (perhaps different than `excerpt`) to show it on the auto-generated category pages.

**Comment by MattDodsonEnglish** [comment]
Thanks! I've done a bit of research to try and think this through.
- I'm not sure about how much we can control SERP text, or whether duplication between the page and the excerpt is bad 
- Some content-rich sites reuse descriptions, others don't
- Now I'm thinking that printing the excerpt at the page should be an option instead of a default. 
- I still think it'd be good to autogenerate the list pages using this `excerpt` though.

## Some questions about SREP text

I don't have any idea about the answer to these questions, but I'm interested to know.

- Can we be sure that Google will show the description?

  A 2020 study found that Google re-writes the description 70% of the time, and the text can differ on mobile and desktop [^1].
  My quick search shows that Google prints k6 excerpts most of the time, but "Running k6" was different (at least in my search.) I don't know if there's something we could or should do to avoid this.

- Is it so bad if the text repeats in the SREP and the top of the page?

   People expect the text to match the page content, so that doesn't seem to bad.

  And since, the excerpt text definitely shows in social shares, and maybe will show in list pages, that would create a "unified experience" between the three main ways a reader could arrive on a page.

## Very informal research summary

I looked at a few websites that I think have good content, or at least that are well-known and should have good content.

| Site               | Page has top-level summary? | Summary is description? |
|      -              |              -              |             -           |
| Nielsen and Norman | Yes                        | Yes                    |
| Animalz            | Sometimes                  | No                     |
| Cancer.gov         | No                         |                        |
| New York Times     | Yes (the lede)             | Sometimes              |
| New Yorker         | Yes                       | Yes (always?)          |
| Google cloud docs  | Sometimes                  | Sometimes              |


This is all to say that people who have thought hard about this problem have both shown and not shown their description as an excerpt. I think there's no clear answer.

## Possible actions

I'm still slightly in favor of reusing the meta-description in pages for the following reasons:
- It would automatically give each page a BLUF, aka bottom-line up front, aka inverted pyramid
- It would cause us to pay more attention to our `description` texts, since they would be visible on each page
- We could reuse it as a description text for our list pages

I favor the BLUF--it lets readers quickly decide whether they want to continue. But I realize there may be pages where the best `excerpt` text would look weird at the top of the page. Maybe we could elect to turn it on with a `showExcerpt` boolean in the front matter.

But we could definitely use it for auto-generated list pages.
For this list, what's wrong with a simple two-column table? It's how we (manually) do for options:

![image](https://user-images.githubusercontent.com/47385188/184634728-b0c4c309-1c6e-409a-8b75-c03236ef1bb0.png)


I also should note that I haven't found much large-scale technical documentation uniformly uses this structure. Only the Doks theme (linked upthread) and readme.io seem come to mind. Nevertheless, I don't think that necessarily means the strategy is bad.

Something that's interesting to note is that documentation pages _written by the Google docs team_ often reuse it, but on other pages they completely leave out meta-description text. For example:
https://cloud.google.com/sql/docs/mysql/features


[^1]: [Google rewrites meta-descriptions over 70% of the time](https://www.searchenginejournal.com/google-rewrites-meta-descriptions-over-70-of-the-time/382140/)

**Comment by bolotskydev** [comment]
Guys, let's not overcomplicate things 😅 

1. If you need to reuse excerpt as `TL;DR`, please, do so manually. Make a heading, copypaste the text, here you go. I don't see why we need to extend the logic with this functionality. It won't be much of a time-saver since we still do write the articles manually. But at least this way the whole generation system will stay a bit more robust.

2. The auto-generated `category` pages do look ugly in fact, they are only placeholders so user won't end up nowhere traversing back the breadcrumbs sequence. The changes you offering totally possible, but require design (at least simple), time and resources to be implemented. It is not so easy as put 2 lines of code. 

3. Concerning the #600 issue which is mentioned here - please, if you want to have every single sidebar heading as link, please, make another file in the proper place.

Again, guys, with the years and features implemented, the system slowly becomes fragile, especially generation logic. We have to carefully pick our battles here, as most of the changes require research, context and rigorous testing no to break anything, especially in terms of SEO.

**Comment by bolotskydev** [comment]
I hate though being the one who drags down the @MattDodsonEnglish 's locomotive of progress :))

**Comment by MattDodsonEnglish** [comment]
Haha that's okay! I appreciate robust discussion.

And in this case, I really thought it would be one or two lines to reuse the frontmatter[^1].  But after the research I did the other week (three posts up), I became much more indifferent about this topic.
I'm going to close this. Thanks for the context!

[^1]: But how hard can it be to reference a page's frontmatter in a text? For example, referencing the the `title` property somewhere in the markdown.  Sometime soon, I'd like  make an exploratory issue about reusing data (frontmatter and separate YAML/JSON files )  to template content. This footnote is a teaser :-)
