### ISSUE TITLE
Make sidebar headings link to summary pages

### ISSUE THREAD

**Issue by MattDodsonEnglish** [grafana/k6-docs#600]
In the JavaScript API docs, the sidebar headings are hypertext. When the readers click a sidebar link, they go to a little section overview. It looks like Gatsby automatically generates a list of pages in that section too.

In all the other docs pages, the sidebar headings are just plain text. But, you can still access the list page by manually typing the URI. 

I think it would improve the information architecture of the docs if these sidebars were clickable and the pages had little descriptions. It would be a little form of progressive disclosure. To take the progressive disclosure further, the list of pages could also include the page's `excerpt`.

![image](https://user-images.githubusercontent.com/47385188/161148091-b4619cc5-5563-4cb3-a5b5-96a0a9cd986e.png)

**Comment by MattDodsonEnglish** [comment]
Here's a pseudo-code prototype of how we could generate the list pages automatically.  I'm using the structure of the Options page that I made manually. It's not fancy but I don't think it's ugly either. I believe having something like this for each sidebar link and dropdown page would improve the Information Architecture of the docs.

![image](https://user-images.githubusercontent.com/47385188/170975509-044b4ff3-4811-46f1-ab0f-829ebbc8f676.png)

**Comment by heitortsergent** [comment]
Closing this since we made the move to the Grafana docs and now all the sidebar headings are individual pages.
