### ISSUE TITLE
Broken link on the Cloud / Analyzing Results / Overview page

### ISSUE THREAD

**Issue by SilencerWeb** [grafana/k6-docs#636]
1. Performance Insights in the first paragraph seem to be broken

![image](https://user-images.githubusercontent.com/20713191/165079120-91e9a9b2-f6c0-428e-9588-7377078e0dad.png)

2. Performance Insights in See Also section leads to Performance Trending. Is it ok?

![image](https://user-images.githubusercontent.com/20713191/165079312-1962c9b7-a09d-4450-ba7c-4760bccf7c78.png)

Link to the page — https://k6.io/docs/cloud/analyzing-results/overview/

cc @ppcano

**Comment by ppcano** [comment]
fixed by https://github.com/grafana/k6-docs/commit/21bdaacf25e234eed3dc757d93bb6f45c80b8df9. Thanks, @SilencerWeb
