### ISSUE TITLE
Broken link on "Ramping arrival rate" page

### ISSUE THREAD

**Issue by ovenal** [grafana/k6-docs#647]
There is the broken "ramping VUs executor" link on the "Ramping arrival rate" page (https://k6.io/docs/using-k6/scenarios/executors/ramping-arrival-rate).  This link points to a non-existing page (https://k6.io/docs/using-k6/scenarios/ramping-vus)

**Comment by javaducky** [comment]
Thanks @ovenal! 🙇  I can get that fixed real quick.
