### ISSUE TITLE
Better design for documenting object properties

### ISSUE THREAD

**Issue by imiric** [grafana/k6-docs#656]
While working on [xk6-browser JS API docs](https://github.com/grafana/k6-docs/issues/582) (WIP branch [`docs/582-xk6-browser`](https://github.com/grafana/k6-docs/tree/docs/582-xk6-browser)) we have to document many methods that receive objects, and it's important to document each property as well.

We're currently experimenting with two approaches for this:

- [Document properties in a separate table and link to it from the object's Description column.](https://github.com/grafana/k6-docs/blob/3416a29a957f2bc3346ddcf28fd985c1c4b13548/src/data/markdown/docs/30%20xk6-browser/01%20xk6-browser/01-browser/05-newcontext--options--.md)
  The problem with this is that it clutters the page with many tables, and forces the user to navigate from the original table to view the properties and then back again, which is not great UX.
  This is mostly in line with how the [k6 docs](https://k6.io/docs/javascript-api/k6-http/batch/) look, but the xk6-browser JS API is much larger, so the approach doesn't scale well.
  It also wouldn't work well with nested objects, as the page would look too cluttered and confusing.

- [Document properties in the same table, right below the object itself.](https://github.com/grafana/k6-docs/commit/3416a29a957f2bc3346ddcf28fd985c1c4b13548#diff-ce3514099e143339d07ca744e875bd6a288d9315af4a26a76ddfd08622e7f740R8-R13)
  I think this is an improvement, and is more in line with how [Playwright](https://playwright.dev/docs/api/class-page#page-pdf) and [Puppeteer](https://pptr.dev/#?product=Puppeteer&version=v13.7.0&show=api-pagepdfoptions) docs look, although they use unordered lists, which can be easily nested.
  This initial version simply prefixes the properties with a hyphen, but we'd like to make it more visually obvious that these are properties of the object above, and not method arguments.

So this issue is to discuss design ideas and ultimately an implementation to improve this.

A good visual cue would be to indent properties and "link them" somehow to the object. E.g.:

```
geolocation
├─ latitude
├─ longitude
└─ accuracy
```

Or for nested props:

```
toplevel
└─ prop
   └─ nested
```

Alternatively, we could shift right the left table border for properties to have something like:

```
| toplevel arg | ... |
  | prop       | ... |
    | nested   | ... |
| another arg  | ... |
```

@inancgumus mentioned having sub-tables for properties and making them collapsible. Sub-tables could work, but I'm not sure if we should add the collapsible feature, as properties should be visible by default. The problem is not so much the amount of options/properties, but having them scattered around the page.

Let us know if you have any ideas to accomplish this. Thanks!

**Comment by inancgumus** [comment]
Thanks, @imiric, for summarizing what we discussed 👍 

I understand the concerns of scattering the options throughout the page. Here are my two cents:

**1st option:** As we agreed on the layout last week, I'm on the side of having separate tables; they look more readable to me.

<img width="602" alt="Screen Shot 2022-05-04 at 16 35 22" src="https://user-images.githubusercontent.com/621232/166692393-1491e7a3-645d-4b12-a803-bb220ad44ef5.png">

**2nd option:** I would not include option properties in the same table. Nested option properties look confusing as if they are parameters of the method itself. Your example of the `geolocation` options looks harmless, but I fear it won't scale well with a big list of options and options that include other options (Figure 1).

<img width="794" alt="Screen Shot 2022-05-04 at 16 33 34" src="https://user-images.githubusercontent.com/621232/166692017-9e5c4daf-d5a8-4425-af12-5538932b3604.png">

**Some ideas:**

* We could shift the option parameters right, but it would look strange. Even then :disappointed:
* We may use a subheader in the same table if CSS allows it. :bulb::thinking_face:

Let's also explore other styling options, as well.

**Comment by imiric** [comment]
My suggestion with hyphens was just a placeholder. It's clear that properties need to be indented and that they should somehow be visually linked to the object, but it needs proper styling. Here's a hack with the pipe symbols:

![2022-05-04-161202_1006x375_scrot](https://user-images.githubusercontent.com/1009277/166704752-1b78847e-08df-44ce-b65a-fbcda91d6ab6.png)

If that could be done in CSS, but more visually pleasing, I wouldn't be against it.

I like the nested table approach :+1: If we could get rid of the repeated "Type" and "Description" headers, have the cells aligned under the same ones as the main table, and also add that missing visual link to the object (or having the subheader be "Properties" instead of "Option"?) it would look less cluttered. But yeah, something like that would be good.

If we can't come up with a better design before next week, then let's release with multiple tables. But again, it's really bad UI/UX I just didn't notice when we were discussing the layout in that PR.

@SilencerWeb WDYT?

**Comment by SilencerWeb** [comment]
Honestly, I think something like Stripe's solution would fit much better, will be easier to support, and will be easier to scale. [Example](https://stripe.com/docs/api/prices/object)

They present objects like this:

![image](https://user-images.githubusercontent.com/20713191/166886747-4ae606ba-d0d2-4a95-bede-8166c66bc875.png)

And have a button that expands nested objects:

![image](https://user-images.githubusercontent.com/20713191/166886858-4f4abbec-8773-4a24-8891-d299692c8720.png)

It's your call, though! Please let me know what you think

cc @imiric @inancgumus

**Comment by imiric** [comment]
@SilencerWeb Indeed, that looks much better! I see two potential problems with it though:

- Abandoning the table UI would go against all the other API docs we currently have, so we'd have to update it site-wide to remain consistent. I wouldn't be against it since that UI is an improvement, but it would be a much larger task than expanding the current table approach to fit this use case better.

- I'm not necessarily a fan of expanding objects, but it does reduce the clutter. I wonder how it looks for several nested objects, though I assume it wouldn't be too problematic. Just keep nesting and expanding... :sweat_smile:

We should get @ppcano's opinion on this and if he agrees with abandoning the table UI across the site. If so, it might not be a big deal to break consistency and introduce this only for xk6-browser, and then change it for the other API docs later.

**Comment by ppcano** [comment]
@imiric, Is abandoning the table UI across the site necessary?

Please, point me if I am missing something.  

My understanding is that at this moment, we have the table UI and use it for all the cases to document APIs. 

This new UI would be a new option to present better the information for one or many particular case/s.


To be concrete, if we bring the object properties layout, I would not change [this table](https://k6.io/docs/javascript-api/k6/):

<img width="899" alt="Screenshot 2022-05-05 at 11 14 08" src="https://user-images.githubusercontent.com/825430/166894605-1636a148-6977-47e4-b936-82627602e8f9.png">



So, I wonder if this an "either-or" option? Or both can coexist. 

> introduce this only for xk6-browser, and then change it for the other API docs later

If both can coexist, the new UI does not introduce any regresions. I totally agree to proceed as you suggest. 

If not, let me double-check the implications.

**Comment by imiric** [comment]
@ppcano The Stripe UI is very different from the table UI we currently use, so keeping both on the site doesn't make much sense, and would look jarring to the user.

The issue is not with that particular table, which only links to each function's page, so I suppose we can keep it intact. The issue is with the function page itself, and how objects are documented. We currently don't have a nice way of doing this since the k6 JS API is much simpler and we haven't run into that many cases that need it.

For example, see the way [`batch()`](https://k6.io/docs/javascript-api/k6-http/batch/) looks. We document the array in a separate table and passing an object is **undocumented**, apart from the examples.

Or how [`http.requests()`] looks, where we document the `params` object in [a separate page](https://k6.io/docs/javascript-api/k6-http/params/), which might make sense in this case since this object is used by a few methods.

But these approaches don't scale well for documenting the xk6-browser API, which is much more complex. See the screenshots Inanc posted above. With several tables on the same page the object properties documentation is scattered and it's difficult to make sense of which properties belong to which object (i.e. the user would have to make a mental note about it while they navigate back and forth).

So, yeah, I don't think both a Stripe-like UI and our current table UI can coexist. Since this will be a larger change if we decide to adopt it, then we might introduce it with the xk6-browser docs and migrate the rest of the site later.

**Comment by inancgumus** [comment]
@ppcano, I'm on the side of using the same table UI we currently use (Figure 1 in my [earlier comment](https://github.com/grafana/k6-docs/issues/656#issuecomment-1117325532)).

For complex nested options, I suggested [Figure 3](https://github.com/grafana/k6-docs/issues/656#issuecomment-1117325532). It also uses the current table UI. We can also add collapsable tables for them on the same table (as @SilencerWeb and I suggested).

**Comment by inancgumus** [comment]
@ppcano, I'm on the side of using the same table UI we currently use (Figure 1 in my [earlier comment](https://github.com/grafana/k6-docs/issues/656#issuecomment-1117325532)). This approach adds tables for each option and lets users read the options on the same page.

@imiric worries that the option tables are cluttering the page and scattering the information. So I suggested another idea for complex nested options in [Figure 3](https://github.com/grafana/k6-docs/issues/656#issuecomment-1117325532). Since my example shifts the nested tables to the right, we can make those tables collapsable. It also uses the current table UI.

> imiric: if he agrees with abandoning the table UI across the site

I think we don't need to abandon the table UI. As supporting collapsable tables won't affect the rest of the k6 docs site. We can still use the same table UI for displaying them when users click on each option (as @SilencerWeb and I suggested). So we can prevent cluttering the page with many tables.

**Comment by inancgumus** [comment]
@SilencerWeb, we decided to move forward as follows:

### First approach
We'll document the nested properties right below their main object property:

![image](https://user-images.githubusercontent.com/621232/167103772-28f89766-e4b4-4897-a49f-da993ef784d0.png)

## Second approach

Then, we want to switch to expandable/collapsable tables. We need your help to do that :)

When users click on the main property of an object (e.g. `geolocation` in the above image), the nested property table (e.g., a table with rows each with `latitude`, `longitude`, `accuracy`) will expand right below the main property.

FYI: @ppcano @imiric

**Comment by SilencerWeb** [comment]
@inancgumus so as I understand, we want to keep the first approach but hide nested properties by default and open / close them by some button click or something, am I right?

**Comment by inancgumus** [comment]
@SilencerWeb, hey!

> we want to keep the first approach

We will create the xk6-browser documentation similar to the `setGeolocation`. So we'll be adding nested properties in the same table (`geolocation.latitude`, `geolocation.longitude`, etc. 

> hide nested properties by default and open / close them by some button click or something

Yep. We need your support for making the nested properties expandable/collapsable in the same table. Some ideas: Parse the nested properties from the table and make the sub-tables automatically expandable/collapsable. Or, provide us a way to do it ourselves.
