### ISSUE TITLE
Incorrect metadata URL in JsAPI docs

### ISSUE THREAD

**Issue by MattDodsonEnglish** [grafana/k6-docs#669]
It seems like the open graph URI is incorrect in the Js API docs. In short, the `/javascript-api/` path is missing from the URI.

To reproduce:
1. Go to https://k6.io/docs/javascript-api/jslib/
2. View source.
3. Search `og:url`.

```html
<meta data-react-helmet="true" property="og:url" content="https://k6.io/docs/jslib/"/>
```

That link is broken. It also appears in the page's `<link>` element.

```html
<link data-react-helmet="true" href="https://k6.io/docs/jslib/" rel="canonical"/
```

Similar broken paths appear in the metadata of the other Jslib pages.

My guess is that the `/javascript-api/` path is missing somewhere in the Gatsby config. 

@ppcano  Thoughts?

**Comment by SilencerWeb** [comment]
Nice catch @MattDodsonEnglish! Thanks a lot!

PR with the fix is ready https://github.com/grafana/k6-docs/pull/673
