### ISSUE TITLE
Improve image support

### ISSUE THREAD

**Issue by MattDodsonEnglish** [grafana/k6-docs#672]
I've noticed a few issues with images. For the first two points, I've added examples.

 * By default, SVGs are outsized for the text.
* PNGs must be preceded by two empty lines to not get stretched. This is not a big deal, of course, but it seems unexpected.
* As far as I can tell, we can't use embedded `<figure>` or `<img>` elements, either.

On this last point, it'd be nice to have a shortcut function to style images as we want. For examples:

```
{ Figure }
img: path/to.png
alt: "Some alt text"
caption: "A caption"
align: left //or right or center
float: true // puts text-side-by-side
border: true // add a border
{ /Figure }
```
That syntax is just pseudocode, just an example of how we could incorporate all the elements. 

I realize these really might be three separate issues, but I just want to document them. I'm happy to close this issue and split it, if that makes more sense.

## Outsized SVGs

![image](https://user-images.githubusercontent.com/47385188/168547270-8ae50d75-9125-4cec-a821-718628cbe779.png)

##  PNGs stretched without two preceding empty lines

|One preceding line|Two preceding lines|
|--|--|
| ![image](https://user-images.githubusercontent.com/47385188/168548712-24ea0177-b2ab-4b11-93d7-79d4f772eb65.png) | ![image](https://user-images.githubusercontent.com/47385188/168549030-354c7649-9d13-484f-802e-65228f67d97c.png)

##

**Comment by bolotskydev** [comment]
Sorry, but I'm afraid there is not much we can do:
- two empty lines - that is totally up to mdx library. We don't own this code a slightest bit, but there is no alternative.
- we don't let content editors affect image position to keep the consistency and sane UI look, sorry. You can only provide media content in a way described in docs. It may sound overly tyrannical, but please, trust the experience :) Anyway, while there are established native ways to operate on media, I doubt we need to spend time implementing the syntax. The cost/benefit ration doesn't look overly good in this case

As of `outsized SVGs` - I don't think I get it. If you mean that they occupy the whole container width all the time - this is intended behavior (see previous point)

**Comment by MattDodsonEnglish** [comment]
For the two empty lines, yeah, agreed. No big deal.

For custom images, it would be nice at least to be able to add a caption. That can be a nice way to make a little side commentary or add context without disrupting the typical reader flow.

It seems reasonable to keep a uniform image presentation for the sake of simplicity, but for the sake of argument, I don't think the risk of content chaos would be so high if any author could use the occasional image float. A counter example is Asciidoc, which has built-in image-position controls. Skimming through [the showcase for Antora](https://gitlab.com/antora/antora.org/-/issues/20) (an Asciidoc SSG), I don't see any disastrous UIs.

But, as I said, it's just for the sake of argument. I realize it's tricky to position images on a site (and for multiple devices), and I'm talking about an entirely different engine, so I can see that the juice is not worth the squeeze. Certainly, I quickly get frustrated when fiddling with images, and my eyes glaze over when reading about graphics.

On that note, I'd never heard of the SVG container until this post :disappointed: , but I'll read up on it :+1: . 
 What I meant by "outsized" is that I'd like to have a  buffer of whitespace between an SVG image and the surrounding text. 
The main reason I'd like to use SVGs is for diagrams. In my understanding, SVGs are better here because:
- They lighten page size
- They scale perfectly
- They are easy to copy and paste into diagrams editors like draw.io, making it easier to update.

If I've made some incorrect assumption about why SVGs are worth using and making formatted nicely, let me know!

**Comment by MattDodsonEnglish** [comment]
Having thought about it more, I'm going to close this issue.
 Currently, there's no specific need for a figure with captions, so there's no need to spend development time making it possible either. If a strong use case comes up, we can make a new issue and task.

I still need to figure out how SVGs work, but that's a another story :grimacing: .
