### ISSUE TITLE
Having a "next version"/"unstable" doc

### ISSUE THREAD

**Issue by mstoykov** [grafana/k6-docs#675]
Currently, if we are documenting JS APIs we make the PR and it stays open until we release the k6 version that it gets introduced at which point we also merge and release a new "version" of the docs. 

This isn't too bad, but it will be kind of nice if we can have "next version"/"stable" instead and we can merge those - potentially even show them (will definitely help with testing). Then when we are releasing a new version of k6 and consequently the docs it just becomes the next version.

**Comment by heitortsergent** [comment]
Closing this since we've moved the docs to Grafana.
