### ISSUE TITLE
Discourage usage of the `k6 login` command?

### ISSUE THREAD

**Issue by na--** [grafana/k6-docs#699]
`k6 login` generally has somewhat poor UX. It creates a `config.json` file deep in the user's home directory (by default), so it often doesn't play well with CI systems and running things in Docker, adding unnecessary steps and complexity. Despite that, it seems like we encourage users to use it instead of just specifying the token via a `K6_CLOUD_TOKEN` environment variable. See these as examples:
- https://k6.io/docs/results-visualization/cloud/
- https://k6.io/docs/cloud/creating-and-running-a-test/cloud-tests-from-the-cli/
- https://k6.io/blog/integrating-load-testing-with-jenkins/
- it's even the first suggestion in https://k6.io/docs/cloud/integrations/token/

This leads to questions like this one: https://github.com/grafana/k6/issues/2570

**Comment by MattDodsonEnglish** [comment]
I am of course always in favor of cutting information that's not needed, but should `k6 login` be de-emphasized totally, or just in containerized contexts?

If I run
```
K6_CLOUD_TOKEN k6 cloud script.js 
```
That wouldn't store the token would it? The main benefit of `k6 login` is that it's a one-time operation right? After that, users can run `k6 cloud script.js`. While writing the environment variable every time wouldn't really matter in an automated situation, wouldn't that be annoying for human fingers on the CLI?

Sorry if I've misunderstood how k6 works here. I definitely agree that it seems that there are too many ways to do the same thing, and we'd improve UX by picking the best option and emphasizing that.

``

**Comment by na--** [comment]
No, no, those are very fair points and you are completely right! `k6 login could` would probably be more convenient on user machines where a one-time login will then allow them to run cloud tests until they change their token. You can sort of achieve the same convenience if you just stick `export K6_CLOUD_TOKEN=...` in your .bashrc file on Linux/Mac/*nix systems, I guess, and that might also be worth mentioning in the docs, but I imagine `k6 login cloud` would be better in the vast majority of cases.

So yeah, you are right, we should encourage `K6_CLOUD_TOKEN` mostly in situations situations where there is no persistence, so CI and/or Docker.

**Comment by MattDodsonEnglish** [comment]
I added a small example in "Cloud tests from the CLI":
https://github.com/grafana/k6-docs/commit/9ffea597a7cfd413c87b98d6c031c43545e3c5de#diff-d6230ae3a41978642417937ad246f286447ce932f11415b5face0dfd3119d886R112-R115


Before closing the issue, I do think we should add a clearer, more findable section of text about how to use env variables in CI builds. We already have an [Automate testing guide](https://k6.io/docs/testing-guides/automated-performance-testing/#create-a-test) which does recommend environment variables, but I don't know that page very well, and I don't know whether it's the first place a reader will look when they want to use k6 in a container or whatever.

Maybe there could be a supplementary "How to incorporate k6 in your CI" how-to guide or example, covering more practical information. The guide seems a bit more theoretical.

**Comment by MattDodsonEnglish** [comment]
With c9793a4e4327e855ad19c1019caae299735e2ca1 and b898015d53b65bddcbfbdb44b12c95b9cb1a4ce2 , I've at least documented that the environment variable is the recommended method for CI authentication.

The docs could still use a more detailed topic about practical aspects of k6 in CI and Containers, but I think this is enough for now.
