### ISSUE TITLE
Better support for admonitions (aka callouts)

### ISSUE THREAD

**Issue by MattDodsonEnglish** [grafana/k6-docs#728]
The docs use admonitions all the time. However each author uses their own style: some add emojis, some add UTF characters, some use `<Blockquote mod="Warning">` function, etc. 

Improving support for admonitions would make them easier to create with an appealing visual format and easier to standardize.

Generally the docs use admonitions for three things:

- _Notes_ for handy tips and extra info
   > **🛈 Notes are very widely used**
   > They are in at least 20 pages
- _Caution_ to tell a user to be careful when following this section
- _Danger_ to tell users about irreversible actions.

The only Gatsby function we have is "Warning". I'd like to also have a blockquote for Notes and Caution. Otherwise, writers have to copy in their own emojis, SVGs, or characters to change the visual style.

Also, I think we could improve the syntax of creating admonitions. How about something like this:

```
<Blockquote mod="[note]|[caution]|[warning]"
title="Here is a title">

Text

</Blockquote>
```

This could generate a stylized admonition with stylized colors, icons, custom headings (`WARNING`), and a title with an ID so that it would create an anchor in the page. 

This would be very similar to how the warning admonition currently works:

```markdown
<Blockquote mod="warning">
#### Title
P1
p2
</Blockquote>
```

This renders nicely, generates a semantic CSS class, and it is pretty easy to write. But I have one complaint: I don't think we should encourage using `<h4s>` for admonitions. Instead, couldn't we have an auto-formatted title with an `id`
 attribute?

**Comment by bolotskydev** [comment]
Hey @MattDodsonEnglish , please, consider the following suggestion concerning admonitions and `dl` element.

<details>
<summary>UI suggestion</summary>

<img width="1600" alt="expand-table" src="https://user-images.githubusercontent.com/32940211/179524002-57fe1a70-8825-47e4-87d9-727700a2214b.png">

</details>

**Comment by MattDodsonEnglish** [comment]
Visually I like it! While there's no title, that would be easy enough to add in markdown `**Like this**`.  Would it have an ID?

> dl element

Sorry, maybe I've missed something. Is there a dl element here?
