### ISSUE TITLE
Document how option consolidation occurs

### ISSUE THREAD

**Issue by na--** [grafana/k6-docs#75]
There used to be a detailed description of how k6 options are "consolidated" at the top of the [options page](https://k6.io/docs/using-k6/options) in the old docs, which I now see has disappeared...  

In essence, we need to explain that the end options are the result of {option defaults + JSON config options + the script exported `options` + environment variables + CLI flags}, in increasing order of precedence. And that this result is saved back into the script `options` before the actual test run starts.

**Comment by na--** [comment]
Ah, my mistake, the explanation has just been moved below the table of contents, https://k6.io/docs/using-k6/options#using-options

which is probably a mistake, given that most people will likely never see it there

**Comment by simskij** [comment]
@ppcano @mostafa lets discuss on wednesday if we have any better solution for this.

**Comment by ppcano** [comment]
Closing it as this is now documented on [How to use options](https://k6.io/docs/using-k6/k6-options/how-to/)
