### ISSUE TITLE
Minor visual issues with the new `TableWithNestedRows` component

### ISSUE THREAD

**Issue by imiric** [grafana/k6-docs#758]
In #757 we noticed that on tables that use the new `TableWithNestedRows` component (great job with that @bolotskydev!), the left border of the expanded sub-table overflows the arrow icon when the row is unusually high:

![2022-08-04-170057_1038x831_scrot](https://user-images.githubusercontent.com/1009277/182885032-19b8ba6b-47f2-4ce1-be20-ff64112ed910.png)

In this case the cell with the default value is 4 lines high, which seems to cause it, as it looks fine on other rows.

I reproduced this in both Firefox v100.0 and Chromium v102 on Linux. @ankur22 also noticed it on macOS.

<hr>

And a super minor detail, but could we center the arrow icon better vertically while we're doing the above change? :smile: I didn't want to create a separate issue for this.

It currently renders a few pixels below the vertical middle of the row:
![2022-08-04-173401_581x136_scrot](https://user-images.githubusercontent.com/1009277/182889215-f1221a78-a31a-4121-9f19-3b9c4062b6fc.png)

Here it is pushed 4 px up in DevTools, which looks much better IMO:
![2022-08-04-174019_600x138_scrot](https://user-images.githubusercontent.com/1009277/182889308-0159aa8e-b459-40e4-bb14-2a986882e44d.png)

Also reproduced in both Firefox v100.0 and Chromium v102.

Thanks! :bow:

**Comment by bolotskydev** [comment]
Thanks @imiric ! It seems to me we didn't take into account such case 😅  I am on it investigating the issue, but at first glance simple sprinkling with additional styles won't do as the 3rd column will still stand out in quite an unpleasant way. I'll see what are the options we have to fix this.

**Comment by imiric** [comment]
Hey, thanks for fixing this @bolotskydev! And apologies for missing the PR. It looks great from the screenshot :)
