### ISSUE TITLE
Breadcrumb URL resolves to wrong link if page title differs slug 

### ISSUE THREAD

**Issue by MattDodsonEnglish** [grafana/k6-docs#763]
Hopefully the title says it all.

Two frontmatter properties that are relevant here:
- `title` makes the `<h1>` and the sidebar text that the reader clicks on
- `slug` makes the URI path.

The breadcrumbs for a page should have hypertext that matches the `title`, with actual anchors towards the `slug`. Right now, though, the breadcrumb goes to the `/<title_text>`. If title differs from slug, this creates a broken link.

Though it's not a big deal in itself, this issue creates broken links that are flagged by the link checker, and all around it would be better if the site doesn't have any 404s. Hopefully the fix is as simple as changing one parameter in the template configuration. 

![image](https://user-images.githubusercontent.com/47385188/183766966-88324d71-c092-42d8-a717-ae9814f21310.png)

**Comment by bolotskydev** [comment]
Thank you for reporting, @MattDodsonEnglish ! I've acknowledged it and explored a bit. My conclusion - it won't be an easy fix due to feature-rich page generation process that increased in complexity over the years. There are certain features that prevent implementation of any simple fix - for example, the ability to alter default file-structure-based page generation with custom frontmatter `slug` field. 

As of now I think we can just remove links on rightmost pieces of any given breadcrumb sequence since it never should be there in the first place, it is a bug. It doesn't even look like link ! 😄  

In the meantime, I'll reexamine the breadcrumbs generation, make necessary changes, and ensure it won't break anything.

**Comment by bolotskydev** [comment]
Thinking of it now, the `slug` field is all-too-powerful and it is not possible to handle all the cases of its misuse. It should be only an alternative for occasionally inconvenient `title` of a file, not a full replacement of the default path generation. 🤔

**Comment by MattDodsonEnglish** [comment]
Hello, thanks for your dilligent investigation! 

It makes total sense to remove the link from the rightmost breadcrumb---it has no purpose.

I also agree _in principle_ with the idea of just removing the slug parameter. I just made an issue about [another slug bug](https://github.com/grafana/k6-docs/issues/771). 

Certainly, I use it just to be lazy about adding redirects. However, I have a few misgivings about removing it yet:

- Some writers have used slugs to get around weird character issues: https://github.com/grafana/k6-docs/tree/8a4f0389e050c7b21a0a17a00a4fc7c79d44122f/src/data/markdown/versioned-js-api/v0.32/javascript%20api/07%20k6-http
- Sometimes the path shouldn't match the title. If the title is very long, the path still could be short.
   - Side note, this more important for directory names and Sidebar links. For example "Creating and running a test" is an okay sidebar title,  but it's an awkwardly verbose path.
   - That is.  I'd much rather `/docs/cloud/run/cloud-tests-from-the-cli` than `/docs/cloud/creating-and-running-a-test/cloud-tests-from-the-cli/`
   - I know it's way beyond the scope of this issue but it's important to note
   
So it seems like there is a definite need to be able to declare paths that differ from titles, but maybe doing it with slugs is too much.

**Comment by bolotskydev** [comment]
@MattDodsonEnglish I've merged the PR that removes the link from the rightmost breadcrumb to ease the problem. 

And to be clear - I don't really want to _completely eliminate_ slug field, I really fancy the functionality you mentioned second, that is, replacing sometimes inconvenient long or cumbersome `title` with a short and sweet version. 😉 

I think we need at least to establish a certain rules, a dev contract so-to-say, like it's okay to alternate the `title`, or even directory path, given that the change is, ehhm, aware of the overall structure and default path length. 

For example:

By default you'd have: `/docs/inconvenient-directory-name/inconvenient-really-long-title`
Valid change: `/docs/inconvenient-directory-name/nice-title` ✅ 
Also valid change: `/docs/nice-directory/nice-title` ✅ 
Invalid change: `/docs/nice-directory/additional-piece-of-path-ignoring-structure/oh-stop/nice-title` ❌ 

The invalid change is hard to be ported to versions/i18n, is hard to be integrated intro breadcrumbs logic (which by default generate stub breadcrumb pages out of path 😄 ), and the mentioned is only tip of an iceberg.

**Comment by bolotskydev** [comment]
> * Some writers have used slugs to get around weird character issues: https://github.com/grafana/k6-docs/tree/8a4f0389e050c7b21a0a17a00a4fc7c79d44122f/src/data/markdown/versioned-js-api/v0.32/javascript%20api/07%20k6-http

Not sure I get it, can you please elaborate? 🤔  May be I can help with this

**Comment by MattDodsonEnglish** [comment]
Sorry, I linked to the wrong file, but a few files in the directory have a slug.
For example:
https://github.com/grafana/k6-docs/blob/7350df4817d9c1e85a83a7e5a7be90f7b33ab440/src/data/markdown/versioned-js-api/v0.34/javascript%20api/08%20k6-http/10-cookieJar--.md


I need to dig through some chats to find the context, but I _believe_ this slug happened to avoid putting a parenthesis in the URL. 
I know there was an effort to remove the arguments from various API method doc while keeping them in the title too.

**Comment by bolotskydev** [comment]
No parenthesis have ever been part of url, it is being stripped since the day 1 🤔  And you are right, #621 PR contains the changes to api url generation you mentioned. 

All things considered, we should use `slug` to affect how `title` of the page should look like, nothing more

**Comment by bolotskydev** [comment]
Also I believe the initial problem with broken links is resolved, though rather unconventional way, so I'm closing this issue for now. I will still contribute to the process though resolving other related to the underlying mechanism issues.
