### ISSUE TITLE
Reference the k6 Cloud YouTube playlist on the Cloud docs

### ISSUE THREAD

**Issue by ppcano** [grafana/k6-docs#785]
https://www.youtube.com/playlist?list=PLJdv3RhAQXNGkRCp7Q0k77n5jif4qjz2o

**Comment by MattDodsonEnglish** [comment]
This seems like a pretty easy fix, but there's one snag.

That cloud overview page is in a JavaScript file at [`src/templates/docs/cloud.js`](https://github.com/grafana/k6-docs/blob/main/src/templates/docs/cloud.js).

I can make a `div` and a class that centers the video. l also need to set the width as a percentage to make it responsive, but that's about all the development I can do. @ppcano Do you think that's sufficient?

Here's a preview:

![image](https://user-images.githubusercontent.com/47385188/189776614-dc96a4fa-4476-405e-a336-e4dbcbad293d.png)

 

@ppcano What do you think? Does this seem like enough?

**Comment by ppcano** [comment]
@MattDodsonEnglish if you are ok, I am ok too. 

The implementation needs to work well on different devices: mobile, tablet, etc.

You can ask the DevTeam (Kirill) if necessary.
