### ISSUE TITLE
Document `k6/experimental/timers`

### ISSUE THREAD

**Issue by mstoykov** [grafana/k6-docs#799]
Added in v0.40.0 the documentation is basically waht is written on MDN about 
* https://developer.mozilla.org/en-US/docs/Web/API/setTimeout 
* https://developer.mozilla.org/en-US/docs/Web/API/clearTimeout
* https://developer.mozilla.org/en-US/docs/Web/API/setInterval
* https://developer.mozilla.org/en-US/docs/Web/API/clearInterval

**Comment by ppcano** [comment]
closed by #836
