### ISSUE TITLE
Missing page https://k6.io/docs/extensions/bundle-builder/

### ISSUE THREAD

**Issue by agilob** [grafana/k6-docs#807]
Missing page or broken link to https://k6.io/docs/extensions/bundle-builder/

on page https://k6.io/docs/getting-started/installation/

![image](https://user-images.githubusercontent.com/2544251/190113823-11c19585-d95e-405f-bf08-fb322b45370e.png)

**Comment by MattDodsonEnglish** [comment]
Thanks for reporting! It should be fixed now.
