### ISSUE TITLE
Searching for terms does not match

### ISSUE THREAD

**Issue by codebien** [grafana/k6-docs#822]
I searched for `custom metrics` and I got not really useful links as the screenshot reports, instead I expected to get:
- https://k6.io/docs/using-k6/metrics#custom-metrics
- https://k6.io/docs/javascript-api/k6-metrics

![2022-10-10-152406](https://user-images.githubusercontent.com/2103732/194876645-f1af1c8e-a9c6-458f-a8a0-4677bc5b448f.png)

**Comment by MattDodsonEnglish** [comment]
Unfortunately, this has been coming up more and more. I'm really not sure how to fix it. It might involve some research into how Algolia works to figure out and modify their indexing.

**Comment by MattDodsonEnglish** [comment]
> I searched for custom metrics and I got not really useful links as the screenshot reports, instead I expected to get:

I think this specific term is fixed, but there are still some others, e.g. `xk6-browser`, that we need to fix. Leaving issue open for now.
