### ISSUE TITLE
Broken link for system tags

### ISSUE THREAD

**Issue by codebien** [grafana/k6-docs#832]
The link for Options in https://k6.io/docs/using-k6/tags-and-groups#system-tags is broken.

https://github.com/grafana/k6-docs/blob/37c2b4271f39b4d8f3d670f5a3d6065ca9bdd402/src/data/markdown/translated-guides/en/02%20Using%20k6/08%20Tags%20and%20Groups.md?plain=1#L50

I guess the good link is: https://k6.io/docs/using-k6/k6-options/reference#system-tags

**Comment by Iam-SilentEyes** [comment]
I will add this

**Comment by MattDodsonEnglish** [comment]
@Iam-SilentEyes 

Sorry to rob the contribution. I missed this issue, but when I saw it I fixed it right away. I don't like to any small breaks wait―just fix them and move on. If you ever catch an obvious fix, feel free to make a PR directly. No need to ask or wait.

If you are interested in contributing to the docs, it  would be a _huge_ help if you could fix some of the other broken links in docs. It's really important necessary work to do to be able to do this: https://github.com/grafana/k6-docs/issues/334

With the linkinator application, you can find broken links here―fix one, fix many, all help would be appreciated.

```linkinator https://k6.io/docs --recurse --skip https://k6.io/docs/javascript-api https://linkedin.com/```


[Skipping JS API for reasons mentioned here: https://github.com/grafana/k6-docs/issues/817]
