### ISSUE TITLE
Too many hyphens

### ISSUE THREAD

**Issue by nicolevanderhoeven** [grafana/k6-docs#841]
I'm seeing some articles that make hyphenates out of words that are not normally hyphenated in the industry, such as `load-testing script`, `test-scenario types`, `load-generator health` , `application-release process`. That last one especially broke my brain for a second as I tried to parse what it means for anything to be `application-release`.

I do not recall ever seeing these terms hyphenated in actual use, and it's painful to look at. In my opinion, it should be `load testing script`, `test scenario types`, `load generator health`, and `application release process`.

@MattDodsonEnglish Can you share your rationale for the hyphens?

**Comment by nicolevanderhoeven** [comment]
Here's my grammatical take on this: phrases like `load testing`, `test scenario`, `load generator`, and `release process` are compound nouns, not adjectives. I think one could argue that `test script`, `load testing script`, `test scenario types` and `load generator health` are compound nouns too. When compound nouns are used _attributively_, that doesn't make them adjectives.

A `test script` is a compound noun just like `washing machine` is. If we add an adjective before that, we don't hyphenate. It's `short test script` and `clean washing machine`, not `short-test script` or `clean-washing machine`.

This isn't a direct comparison, though, because I also think `load test script` and `load test` are compound nouns. I would write `well-written load test script`, for example, just like I would write `front-loading washing machine`.

**Comment by MattDodsonEnglish** [comment]
Sorry I edited my first response severely, I don't know why I was so verbose. I think it was one of those situations where I didn't have time to write a shorter one.

> There are best practices I'd recommend for load tests scripts that I would not recommend for functional test scripts, and k6 can do both (to some extent)

I bet many times the practice is more about the logic than the  _script_. Or, maybe I'm wrong: just out of curiosity, is there an example of testing styles having different scripting practices (like "less imports" or whatever).

  Even when we want to talk about a script, there are workarounds like:
- If the script is for a load test, you shouldn't put ascii art in the comments.
- When scripting load tests, don't put ascii art in the comments.
- Scripts for load tests shouldn't have ascii art in the comments.

I don't think "Load-test scripts shouldn't have ascii art" is bad. I even don't think that "Load test scripts shouldn't have ascii art is bad". :slightly_smiling_face: 

The thing is, against the hopes of grammarians and punctuationalists, we can never be sure that what we write is going to be interpreted in the way that we mean. This risk of secondary meanings increases with concision (almost all short words can mean many things). 

Of course, there's a tradeoff: the more we write to clarify a position, the less it is that the reader will actually read it.

I'm going to close this issue. Thanks for bringing it up! I am sure you weren't the only one, and now I'm going to try to restrain my hyphenation. I'll see who long I can go before writing X-x script.

----

P.s. "A functional testing script" could be different from a "Functional-testing script". One is a testing script that functions, the other is a script that does functional testing.
