### ISSUE TITLE
404s pages

### ISSUE THREAD

**Issue by ppcano** [grafana/k6-docs#855]
- https://k6.io/docs/cloud/your-plan/data-retention
- https://k6.io/docs/cloud/your-plan/data-retention/
- https://k6.io/docs/cloud/your-plan/subscription/
- https://k6.io/docs/cloud-rest-api/test-runs
- https://k6.io/docs/get-started/k6-resources/
- https://k6.io/docs/get-started/results-output/json
- https://k6.io/docs/javascript-api/jslib/aws/kmsclient/kmsclient-generate-data-key/
- https://k6.io/docs/javascript-api/jslib/aws/s3client/deleteObject
- https://k6.io/docs/javascript-api/jslib/aws/s3client/getObject
- https://k6.io/docs/javascript-api/jslib/aws/s3client/listObjects
- https://k6.io/docs/javascript-api/jslib/aws/s3client/putObject
- https://k6.io/docs/javascript-api/jslib/aws/secretsmanagerclient/secretsmanagerclient-putsecret-secretid-secretstring-versionid-tags
- https://k6.io/docs/javascript-api/jslib/aws/secretsmanagerclient/secrett
- https://k6.io/docs/javascript-api/k6-experimental/redis/client/client-sendCommand
- https://k6.io/docs/javascript-api/xk6-browser/page/goto/
- https://k6.io/docs/javascript-api/xk6-browser/page/waitfornavigation
- https://k6.io/docs/javascript-api/xk6-browser/page/waitforselector
- https://k6.io/docs/javascript-apijslib/
- https://k6.io/docs/javascript-apijslib/aws/
- https://k6.io/docs/javascript-apijslib/aws/awsconfig/
- https://k6.io/docs/javascript-apijslib/aws/kmsclient/
- https://k6.io/docs/javascript-apijslib/aws/kmsclient/kmsclient-generatedatakey/
- https://k6.io/docs/javascript-apijslib/aws/kmsclient/kmsclient-listkeys/
- https://k6.io/docs/javascript-apijslib/aws/kmsclient/kmsdatakey/
- https://k6.io/docs/javascript-apijslib/aws/kmsclient/kmskey/
- https://k6.io/docs/javascript-apijslib/aws/s3client/
- https://k6.io/docs/javascript-apijslib/aws/s3client/bucket/
- https://k6.io/docs/javascript-apijslib/aws/s3client/object/
- https://k6.io/docs/javascript-apijslib/aws/s3client/s3client-deleteobject-bucketname-objectkey/
- https://k6.io/docs/javascript-apijslib/aws/s3client/s3client-getobject-bucketname-objectkey/
- https://k6.io/docs/javascript-apijslib/aws/s3client/s3client-listbuckets/
- https://k6.io/docs/javascript-apijslib/aws/s3client/s3client-listobjects-bucketname-prefix/
- https://k6.io/docs/javascript-apijslib/aws/s3client/s3client-putobject-bucketname-objectkey-data/
- https://k6.io/docs/javascript-apijslib/aws/secretsmanagerclient/
- https://k6.io/docs/javascript-apijslib/aws/secretsmanagerclient/secret/
- https://k6.io/docs/javascript-apijslib/aws/secretsmanagerclient/secretsmanagerclient-createsecret-name-secretstring-description-versionid-tags/
- https://k6.io/docs/javascript-apijslib/aws/secretsmanagerclient/secretsmanagerclient-deletesecret-secretid-{-recoverywindow-30-norecovery-false}}/
- https://k6.io/docs/javascript-apijslib/aws/secretsmanagerclient/secretsmanagerclient-getsecret-secretid/
- https://k6.io/docs/javascript-apijslib/aws/secretsmanagerclient/secretsmanagerclient-listsecrets/
- https://k6.io/docs/javascript-apijslib/aws/secretsmanagerclient/secretsmanagerclient-putsecretvalue-secretid-secretstring-versionid-tags/
- https://k6.io/docs/javascript-apijslib/aws/systemsmanagerclient/
- https://k6.io/docs/javascript-apijslib/aws/systemsmanagerclient/systemsmanagerclient-getparameter/
- https://k6.io/docs/javascript-apijslib/aws/systemsmanagerclient/systemsmanagerparameter/
- https://k6.io/docs/javascript-apijslib/httpx/
- https://k6.io/docs/javascript-apijslib/httpx/addheader-key-value/
- https://k6.io/docs/javascript-apijslib/httpx/addheaders-object/
- https://k6.io/docs/javascript-apijslib/httpx/addtag-key-value/
- https://k6.io/docs/javascript-apijslib/httpx/addtags-object/
- https://k6.io/docs/javascript-apijslib/httpx/batch-requests/
- https://k6.io/docs/javascript-apijslib/httpx/clearheader-name/
- https://k6.io/docs/javascript-apijslib/httpx/cleartag-name/
- https://k6.io/docs/javascript-apijslib/httpx/delete-url-body-params/
- https://k6.io/docs/javascript-apijslib/httpx/get-url-body-params/
- https://k6.io/docs/javascript-apijslib/httpx/patch-url-body-params/
- https://k6.io/docs/javascript-apijslib/httpx/post-url-body-params/
- https://k6.io/docs/javascript-apijslib/httpx/put-url-body-params/
- https://k6.io/docs/javascript-apijslib/httpx/request-method-url-body-params/
- https://k6.io/docs/javascript-apijslib/httpx/setbaseurl-url/
- https://k6.io/docs/javascript-apijslib/k6chaijs/
- https://k6.io/docs/javascript-apijslib/k6chaijs/config/
- https://k6.io/docs/javascript-apijslib/k6chaijs/describe-name-function/
- https://k6.io/docs/javascript-apijslib/k6chaijs/error-handling/
- https://k6.io/docs/javascript-apijslib/k6chaijs/expect/
- https://k6.io/docs/javascript-apijslib/utils/
- https://k6.io/docs/javascript-apijslib/utils/findbetween-content-left-right-repeat/
- https://k6.io/docs/javascript-apijslib/utils/normaldistributionstages-maxvus-durationseconds-numberofstages/
- https://k6.io/docs/javascript-apijslib/utils/randomintbetween-min-max/
- https://k6.io/docs/javascript-apijslib/utils/randomitem-array/
- https://k6.io/docs/javascript-apijslib/utils/randomstring-length-charset/
- https://k6.io/docs/javascript-apijslib/utils/uuidv4/
- https://k6.io/docs/misc/glossary/k6.io/docs/using-k6/thresholds
- https://k6.io/docs/results-visualization/
- https://k6.io/docs/results-visualization/grafana-cloud/
- https://k6.io/docs/using-k6/k6-options/how-to-use-options/
- https://k6.io/docs/using-k6/k6-options/options-reference/
- https://k6.io/docs/xk6-browser/
- https://k6.io/docs/xk6-browser/browser/
- https://k6.io/docs/xk6-browser/browser/close/
- https://k6.io/docs/xk6-browser/browser/contexts/
- https://k6.io/docs/xk6-browser/browser/isconnected/
- https://k6.io/docs/xk6-browser/browser/newcontext/
- https://k6.io/docs/xk6-browser/browser/newpage/
- https://k6.io/docs/xk6-browser/browser/on/
- https://k6.io/docs/xk6-browser/browser/version/
- https://k6.io/docs/xk6-browser/browsercontext/
- https://k6.io/docs/xk6-browser/browsercontext/browser/
- https://k6.io/docs/xk6-browser/browsercontext/clearcookies/
- https://k6.io/docs/xk6-browser/browsercontext/clearpermissions/
- https://k6.io/docs/xk6-browser/browsercontext/close/
- https://k6.io/docs/xk6-browser/browsercontext/grantpermissions/
- https://k6.io/docs/xk6-browser/browsercontext/newpage/
- https://k6.io/docs/xk6-browser/browsercontext/pages/
- https://k6.io/docs/xk6-browser/browsercontext/setdefaultnavigationtimeout/
- https://k6.io/docs/xk6-browser/browsercontext/setdefaulttimeout/
- https://k6.io/docs/xk6-browser/browsercontext/setgeolocation/
- https://k6.io/docs/xk6-browser/browsercontext/setoffline/
- https://k6.io/docs/xk6-browser/browsercontext/waitforevent/
- https://k6.io/docs/xk6-browser/browsertype/
- https://k6.io/docs/xk6-browser/browsertype/executablepath/
- https://k6.io/docs/xk6-browser/browsertype/launch/
- https://k6.io/docs/xk6-browser/browsertype/name/
- https://k6.io/docs/xk6-browser/elementhandle/
- https://k6.io/docs/xk6-browser/frame/
- https://k6.io/docs/xk6-browser/jshandle/
- https://k6.io/docs/xk6-browser/keyboard/
- https://k6.io/docs/xk6-browser/locator/
- https://k6.io/docs/xk6-browser/locator/check/
- https://k6.io/docs/xk6-browser/locator/click/
- https://k6.io/docs/xk6-browser/locator/dblclick/
- https://k6.io/docs/xk6-browser/locator/dispatchevent/
- https://k6.io/docs/xk6-browser/locator/fill/
- https://k6.io/docs/xk6-browser/locator/focus/
- https://k6.io/docs/xk6-browser/locator/getattribute/
- https://k6.io/docs/xk6-browser/locator/hover/
- https://k6.io/docs/xk6-browser/locator/innerhtml/
- https://k6.io/docs/xk6-browser/locator/innertext/
- https://k6.io/docs/xk6-browser/locator/inputvalue/
- https://k6.io/docs/xk6-browser/locator/ischecked/
- https://k6.io/docs/xk6-browser/locator/isdisabled/
- https://k6.io/docs/xk6-browser/locator/iseditable/
- https://k6.io/docs/xk6-browser/locator/isenabled/
- https://k6.io/docs/xk6-browser/locator/ishidden/
- https://k6.io/docs/xk6-browser/locator/isvisible/
- https://k6.io/docs/xk6-browser/locator/press/
- https://k6.io/docs/xk6-browser/locator/selectoption/
- https://k6.io/docs/xk6-browser/locator/tap/
- https://k6.io/docs/xk6-browser/locator/textcontent/
- https://k6.io/docs/xk6-browser/locator/type/
- https://k6.io/docs/xk6-browser/locator/uncheck/
- https://k6.io/docs/xk6-browser/locator/waitfor/
- https://k6.io/docs/xk6-browser/mouse/
- https://k6.io/docs/xk6-browser/page/
- https://k6.io/docs/xk6-browser/request/
- https://k6.io/docs/xk6-browser/response/
- https://k6.io/docs/xk6-browser/touchscreen/
- https://k6.io/javascript-api/xk6-browser/locator

**Comment by MattDodsonEnglish** [comment]
(Posting to link issues) besides these, we also have some broken links in the metadata


https://github.com/grafana/k6-docs/issues/817
