### ISSUE TITLE
Using the Enter key to initiate search reloads the page

### ISSUE THREAD

**Issue by going-confetti** [grafana/k6-docs#868]
#### Summary
Using the Enter key to submit the search form reloads the page. I guess we should either prevent this from happening or redirect the user to a page with all search results.

#### Reproduction steps
1. Open the k6 docs: https://k6.io/docs/
2. Type a search term into the search field
3. Hit `Enter` - the page will simply reload

https://user-images.githubusercontent.com/3773351/200008375-b2a6868c-b5de-43f6-b3bb-1088ee750100.mov

**Comment by MattDodsonEnglish** [comment]
Thanks. There's a chance that this is just how Algolia search works--need to research--but I see it's annoying either way. If a mouse is inconvenient for you, I think you can select results with tab too.

Another search-related UX issue is:
#822
