### ISSUE TITLE
Nitpick: unnecessary "0" in the navigation

### ISSUE THREAD

**Issue by sniku** [grafana/k6-docs#885]
https://k6.io/docs/javascript-api/

![image](https://user-images.githubusercontent.com/442646/201343551-3e1d32d5-0046-4ee4-8cbb-c7cfff0e339b.png)

**Comment by MattDodsonEnglish** [comment]
It's a problem with Error codes down the sidebar too. This happens when the sidebar category has only one page, and no directory. I suppose Gatsby is reporting the number of child pages.
