### ISSUE TITLE
Incorrect `og:urls` generated for some pages.

### ISSUE THREAD

**Issue by MattDodsonEnglish** [grafana/k6-docs#899]
@sashasushko's work in #886 surfaced a number of broken links that appear in the meta data. As with #771, #772, and #669 , the break happens with the `og:url`. Besides whatever harm these breaks do for social shares or SEO, the extra broken links also cause a lot of noise, making it harder to remove human-created link rot.

You can review the [logs of broken links](https://github.com/grafana/k6-docs/actions/runs/3479124301/jobs/5817526912). This issue probably manifests in every broken link that seems to refer to its own self.

I'm seeing two different categories of bad `og:url` generation. 

- **In xk6-browser**. Probably everyone of the broken links that ends with `-options`.
   - All of these broken meta-links are missing the `/docs/` path.
    - They also have `-options` prepended at the end, while the slug does not. Yet, this might automatically redirect? 
    
   ![image](https://user-images.githubusercontent.com/47385188/202195227-f30445cc-6a38-4044-a455-55c4bd5c854f.png)
   
 - **For pages with declared slugs**. For example:
 
   ```
   https://staging.k6.io/docs/using-k6/k6-options/reference
   [404] https://staging.k6.io/docs/using-k6/k6-options/options-reference/
   ```
   
  -----
   
   - [ ] Fix Gatsby to generate correct metaURLs
   - [ ] Remove skipped metaURLs from linkinator config

**Comment by MattDodsonEnglish** [comment]
Note that, when the xk6-disruptor PR merges: https://github.com/grafana/k6-docs/pull/891, I think the exact same problem of skipping the `javascript-api` path will happen.

**Comment by MattDodsonEnglish** [comment]
The issue described in #909, if related, is maybe more serious, because it creates a seriously confusing writing UX, which is almost sure to translate into hardcoded URLs or broken links for readers.

**Comment by yasell** [comment]
Hi @MattDodsonEnglish!

I've delved into the problem and seem to have fixed this and similar issues at the [staging](https://staging.k6.io/docs/).
🙏 Please review and let me know if anything is wrong

**Comment by MattDodsonEnglish** [comment]
Hmm, let's see what happens here :-) . 
[1600f08](https://github.com/grafana/k6-docs/commit/1600f08fbe0af10ea48bba243c066d5f90dcc89a) 

If all goes well, the linkchecker should pass completely.

**Comment by MattDodsonEnglish** [comment]
Hooray! Looks fixed---of course, the link checker uncovered another broken link :joy: . https://github.com/grafana/k6-docs/actions/runs/3621231628/jobs/6104661717

 It's unrelated to this though, and I think I can fix it. Thanks, @yasell . Closing this issue.
 
 Related commits:
 
- https://github.com/grafana/k6-docs/commit/4ddb04a77b007fc4744400d2dcf2098b13f6a7a4
- https://github.com/grafana/k6-docs/commit/354c188f1772270b09155303b04bba0dc0a0fdf5
- https://github.com/grafana/k6-docs/commit/c2a092ae3021b5a38f8540f599b7d73bf2de66f2
