### ISSUE TITLE
xk6-browser API Page.locator link is broken

### ISSUE THREAD

**Issue by andrewslotin** [grafana/k6-docs#908]
The [`page.locator()` link](https://github.com/grafana/k6-docs/blob/f6ae06912a63e4ddb9e6c78866aee442f4f9a307/src/data/markdown/docs/30%20xk6-browser/02%20API/10-page.md?plain=1#L39) at the xk6-browser `Page` docs is broken and leads to https://k6.io/javascript-api/xk6-browser/api/locator instead of https://k6.io/docs/javascript-api/xk6-browser/api/locator.

**Comment by MattDodsonEnglish** [comment]
Hmm. I guess this page somehow doesn't set `/docs` as its root path. Probably related to the issue in #899 .

**Comment by MattDodsonEnglish** [comment]
Ironically, skipping the path to avoid the afformentioned bug, the linkchecker skipped this real broken path.
