### ISSUE TITLE
Document best practices to install extensions with Docker 

### ISSUE THREAD

**Issue by immavalls** [grafana/k6-docs#920]
It would be great to document https://community.k6.io/t/how-do-i-install-extensions-when-im-running-the-k6-docker-image/2050. Some extensions like [k6-sql](https://github.com/grafana/xk6-sql/blob/master/Dockerfile) have Dockerfiles, or [xk6-kafka/issues/13](https://github.com/mostafa/xk6-kafka/issues/13) documents a best practice.

**Comment by javaducky** [comment]
As fate would have it, I have an OKR for this quarter to put together a guide for building customized k6 with extensions by using Docker.

**Comment by immavalls** [comment]
Nice, @javaducky I also saw your https://github.com/javaducky/k6-office-hours-047/blob/main/Dockerfile.

**Comment by immavalls** [comment]
Apart from the docs on how to [create extensions using docker](https://k6.io/docs/extensions/guides/build-a-k6-binary-using-docker/), it does seem that we could benefit from having an example that showcases how to run with docker similar to https://community.k6.io/t/how-can-i-create-a-docker-compose-in-order-to-run-docker-build-and-run-in-it/6502/8. I can piece this together from different extensions, but maybe an example in https://k6.io/docs/examples/ can help, or somewhere else in the docs.

**Comment by immavalls** [comment]
Thanks @imiric, then maybe we can close this issue? The docs already contain examples how to eun wirh docker, and in the forum and github repos people can find docker compose examples.
