### ISSUE TITLE
Set image captions on k6 Cloud docs

### ISSUE THREAD

**Issue by ppcano** [grafana/k6-docs#942]
The [k6 Cloud docs](https://k6.io/docs/cloud/) uses many images to show the product UI.

Adding captions to some images will improve the content of these articles.

Below is an example:

<img width="882" alt="Screenshot 2022-12-09 at 13 39 05" src="https://user-images.githubusercontent.com/825430/206704404-84d59e69-86c1-49fe-8573-960e0b6015b5.png">

**Comment by MattDodsonEnglish** [comment]
@ppcano  Now that we also have the Grafana cloud k6 docs, I'm not sure this is worth it.

What do you think?
