### ISSUE TITLE
Improve documentation versioning

### ISSUE THREAD

**Issue by imiric** [grafana/k6-docs#966]
The current way of documenting specific k6 versions (introduced in #283) has some drawbacks and limitations:

- The process involves duplicating the entire `javascript api` tree, which is inefficient and bloats the repository, but more importantly carries layout and content changes that need to be repeated on all versions to be consistent.
  If you take a look at [the landing page for the latest v0.42.0 version](https://k6.io/docs/javascript-api/), you'll see that the "Init context" explanation is different from v0.40.0 and earlier. If we need to make layout or style changes, it needs to be done on all versioned copies.

- It only versions JS API docs. Sometimes we make changes to [k6 options](https://k6.io/docs/using-k6/k6-options/reference/), but there's no way for the user to see which version is documented. So we resort to phrases like "New since v...", which often goes stale, and is not relevant after those versions are widely deployed. See the discussion in https://github.com/grafana/k6-docs/pull/965#discussion_r1055905689.

- It doesn't version any of the extension docs. xk6-browser and xk6-disruptor are stuck with "latest". This documentation shouldn't be only under the "JavaScript API" section, since it has an introduction, installation, "Getting started" guides, etc., but maybe that's a separate issue.

I don't have a specific proposal for fixing this, but I'm happy to brainstorm some solutions with the PixelPoint team.

**Related issues:** #675, #955

**Comment by ppcano** [comment]
> you'll see that the "Init context" explanation is different from v0.40.0 and earlier. If we need to make layout or style changes, it needs to be done on all versioned copies.

Why? I am not sure this is a must. My approach is to fix the latest version and the old ones are unmaintained (saved for reference).

> So we resort to phrases like "New since v...", which often goes stale

Agree. We should do better on updating these notes. 

After how many new versions should we drop the version note? 2, 4, 6, 8?

> It doesn't version any of the extension docs. xk6-browser and xk6-disruptor are stuck with "latest". 

Agree. This has been considered internally but not prioritized.

**Comment by heitortsergent** [comment]
Closing this since we've moved the docs to Grafana.
