### ISSUE TITLE
Debian/Ubuntu installation is no longer valid

### ISSUE THREAD

**Issue by ivan-velasco** [grafana/k6-docs#971]
https://k6.io/docs/get-started/installation/#debian-ubuntu

The artifact url is no longer valid `https://dl.k6.io/deb stable main`

The correct url now seems to be `https://dl.k6.io/deb/dists/stable/ main`

Run in jenkinsfile
> echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb/dists/stable/ main | tee /etc/apt/sources.list.d/k6.list"

**Jenkinsfile run error**
```
echo deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb/dists/stable/ main
tee /etc/apt/sources.list.d/k6.list
deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb/dists/stable/ main
apt-get update
E: Malformed entry 1 in list file /etc/apt/sources.list.d/k6.list (Component)
E: The list of sources could not be read.
```

**Comment by na--** [comment]
My apologies, an infrastructure change broke [dl.k6.io](https://dl.k6.io). It should now be fixed, can you please confirm that the Debian install instructions now work for you, without any changes to them?

**Comment by ivan-velasco** [comment]
@na-- Thanks for the help. Instructions are working now successfully.
