### ISSUE TITLE
Review xk6-disruptor kubecdtl command syntax

### ISSUE THREAD

**Issue by immavalls** [grafana/k6-docs#975]
As reported in https://community.k6.io/t/k6-documentation-change-service-type-of-kubernetes-service/5659, we need to [review the docs](https://k6.io/docs/javascript-api/xk6-disruptor/get-started/expose-your-application/) for the command `kubectl -n namespace patch svc service -p '{"spec": {"type": "LoadBalancer"}}'`

cc: @pablochacin

**Comment by pablochacin** [comment]
I checked the syntax is correct in Linux. I'm pretty sure this is an issue with quotes in Windows shell.

**Comment by pablochacin** [comment]
Fixed by https://github.com/grafana/k6-docs/pull/986
