### ISSUE TITLE
Update xk6-browser docs for the new async/await API

### ISSUE THREAD

**Issue by inancgumus** [grafana/k6-docs#979]
We decided to update the blog posts and documentation to await/async before releasing the xk6-browser version.

You can see the updated examples for reference in https://github.com/grafana/xk6-browser/issues/697.

**Comment by inancgumus** [comment]
@ankur22 @mdcruz Should we start doing this?

**Comment by mdcruz** [comment]
> @ankur22 @mdcruz Should we start doing this?

I have created https://github.com/grafana/k6-docs/pull/996 :)

**Comment by mdcruz** [comment]
Now completed. See https://k6.io/docs/javascript-api/k6-browser/
