### ISSUE TITLE
k6-docs/CONTRIBUTING/ steps do not work on windows

### ISSUE THREAD

**Issue by srperf** [grafana/k6-docs#980]
Running the npm start command on windows prompts me:
> shx test -f ./.env.development || shx cp ./.env.example ./.env.development

'shx' is not recognized as an internal or external command,
operable program or batch file.

**Comment by MattDodsonEnglish** [comment]
https://github.com/shelljs/shx/issues/164#issuecomment-899666050

**Comment by srperf** [comment]
It was super simple.
It required:
npm install shx
I will add it in a chance later ;)

**Comment by srperf** [comment]
Tried the commands proposed and it worked.
