### ISSUE TITLE
Add parameter to show h3s in Tables of contents

### ISSUE THREAD

**Issue by MattDodsonEnglish** [grafana/k6-docs#998]
The docs site shows only h2s for the in-page ToC. In most cases, this is fine, but for long articles, it could improve scannability to extend the table of contents to h3s. This is especially true in docs like the testing guides, where the content  is long and has many facets.

**Comment by ppcano** [comment]
We'll be moving testing guides to the blog. Then, on which other pages will the H3 ToC be necessary?

**Comment by MattDodsonEnglish** [comment]
That's true. The only time I really miss it is in these long articles anyway.
